openapi: 3.1.0
info:
  title: Hack for Facts - Public Spending API
  description: REST endpoints designed for AI agents and tools to fetch Romanian
    public spending data in a compact, structured format.
  version: 1.0.0
components:
  schemas: {}
paths:
  /ai/v1/entities/search:
    get:
      operationId: getEntitiesSearch
      summary: Find public institutions.
      tags:
        - AI
      description: Use this to help the user find a specific public institution when
        their query is ambiguous or they don't know the exact name or CUI
        (fiscal identifier). Returns a list of potential matches that the user
        can choose from.
      parameters:
        - schema:
            type: string
          in: query
          name: search
          required: true
        - schema:
            type: integer
            minimum: 1
            maximum: 10
          in: query
          name: limit
          required: false
        - schema:
            type: integer
            minimum: 0
          in: query
          name: offset
          required: false
      responses:
        "200":
          description: Default Response
  /ai/v1/entities/details:
    get:
      operationId: getEntityDetails
      summary: Get high-level financial totals for an entity.
      tags:
        - AI
      description: Returns one-year totals (income and expenses) for a selected
        entity. Use for high-level questions like “How much did [entity] spend
        in <year>?”. Prefer 'entityCui' (exact); otherwise use 'entitySearch'
        (fuzzy). Include 'year'. Response contains a deep link at 'data.link'.
      parameters:
        - schema:
            type: string
          in: query
          name: entityCui
          required: false
          description: Exact CUI (fiscal identifier) of the entity. Always prefer using
            this over 'search' if the CUI is known, as it guarantees an exact
            match.
        - schema:
            type: string
          in: query
          name: entitySearch
          required: false
          description: "Free-text fuzzy search. Use this when the CUI is unknown. Note:
            this returns the single best match, which may not be correct if the
            name is ambiguous."
        - schema:
            type: integer
            minimum: 2016
            maximum: 2100
            default: 2024
          in: query
          name: year
          required: false
          description: Reporting year for snapshot totals and execution lines
      responses:
        "200":
          description: Default Response
  /ai/v1/entities/budget-analysis:
    get:
      operationId: getEntityBudgetAnalysis
      summary: Income and spending grouped by functional category (overview).
      description: One-year overview of income and expenses grouped by functional
        category (e.g., education, health, transport), sorted by amount.
        Identify entity by 'cui' or 'search'; 'year' is required. Response
        includes a deep link. For deep dives, use the functional or economic
        endpoints.
      parameters:
        - schema:
            type: string
          in: query
          name: cui
          required: false
          description: Exact CUI of the entity (preferred when known).
        - schema:
            type: string
          in: query
          name: search
          required: false
          description: Free-text fuzzy search when CUI is unknown.
        - schema:
            type: integer
            minimum: 2016
            maximum: 2024
            default: 2024
          in: query
          name: year
          required: true
          description: Reporting year for the spending summary.
      responses:
        "200":
          description: Default Response
  /ai/v1/entities/budget-analysis-by-functional:
    get:
      operationId: getEntityBudgetAnalysisSpendingByFunctional
      summary: Deep dive by functional code (chapter or full code).
      description: "Detailed breakdown for a single functional area. Accepts a 2-digit
        chapter (e.g., '65') or a full functional code (e.g., '65.04.02').
        Required: 'entityCui', 'year', 'functionalCode'. Includes totals and,
        where applicable, economic composition. Response includes a deep link."
      parameters:
        - schema:
            type: string
          in: query
          name: entityCui
          required: true
          description: Exact CUI of the entity.
        - schema:
            type: integer
            minimum: 2016
            maximum: 2024
            default: 2024
          in: query
          name: year
          required: true
          description: Reporting year for the spending summary.
        - schema:
            type: string
          in: query
          name: functionalCode
          required: true
          description: Functional code to filter the breakdown. Use a 2-digit chapter
            (e.g., '65') or a full code (e.g., '65.04.02').
      responses:
        "200":
          description: Default Response
  /ai/v1/entities/budget-analysis-by-economic:
    get:
      operationId: getEntityBudgetAnalysisSpendingByEconomic
      summary: Deep dive by economic code (e.g., '10.01.01').
      description: "Detailed breakdown filtered by an economic classification code
        (dotted format, e.g., '10.01.01'), showing where that code contributes
        across functional areas. Required: 'entityCui', 'year', 'economicCode'.
        Response includes a deep link."
      parameters:
        - schema:
            type: string
          in: query
          name: entityCui
          required: true
          description: Exact CUI of the entity.
        - schema:
            type: integer
            minimum: 2016
            maximum: 2024
            default: 2024
          in: query
          name: year
          required: true
          description: Reporting year for the spending summary.
        - schema:
            type: string
          in: query
          name: economicCode
          required: true
          description: Economic code to filter the breakdown; dotted format like '10.01.01'.
      responses:
        "200":
          description: Default Response
servers:
  - url: https://related-kiwi-epic.ngrok-free.app
tags:
  - name: AI
    description: AI-friendly simplified and aggregated endpoints
  - name: Health
    description: Health check endpoints
