openapi: 3.1.0
info:
  title: Hack for Facts - Public Spending API
  description: REST endpoints designed for AI agents and tools to fetch Romanian
    public spending data in a compact, structured format.
  version: 1.0.0
components:
  schemas: {}
paths:
  /ai/v1/entities/search:
    get:
      operationId: getEntitiesSearch
      summary: Search entities by name/address/CUI (fuzzy)
      tags:
        - AI
      parameters:
        - schema:
            type: string
          in: query
          name: search
          required: true
        - schema:
            type: integer
            minimum: 1
            maximum: 10
          in: query
          name: limit
          required: false
        - schema:
            type: integer
            minimum: 0
          in: query
          name: offset
          required: false
      responses:
        "200":
          description: Default Response
  /ai/v1/entities/details:
    get:
      operationId: getEntityDetails
      summary: Entity details by cui or search
      tags:
        - AI
      description: Provides a summary of an entity's expenses and incomes for a given year.
      parameters:
        - schema:
            type: string
          in: query
          name: cui
          required: false
          description: Exact CUI of the entity (preferred when known)
        - schema:
            type: string
          in: query
          name: search
          required: false
          description: Free-text fuzzy search across name/address/CUI; first match is used
            when CUI is not provided
        - schema:
            type: integer
            minimum: 2016
            maximum: 2100
            default: 2024
          in: query
          name: year
          required: false
          description: Reporting year for snapshot totals and execution lines
      responses:
        "200":
          description: Default Response
  /ai/v1/entities/budget-analysis:
    get:
      operationId: getEntityBudgetAnalysis
      summary: Get a summary of an entity's spending and income by main functional
        classification (Classification of the Functions of Government). Useful
        if you need entity data about education, transport, health, etc.
      tags:
        - AI
      description: Provides a summary of an entity's expenses and incomes for a given
        year using functional classification grouping and sorted by amount.
        Useful if you need entity data about education, transport, health, etc.
      parameters:
        - schema:
            type: string
          in: query
          name: cui
          required: false
          description: Exact CUI of the entity.
        - schema:
            type: string
          in: query
          name: search
          required: false
          description: Free-text fuzzy search for the entity.
        - schema:
            type: integer
            minimum: 2016
            maximum: 2024
            default: 2024
          in: query
          name: year
          required: true
          description: Reporting year for the spending summary.
      responses:
        "200":
          description: Default Response
servers:
  - url: https://related-kiwi-epic.ngrok-free.app
tags:
  - name: AI
    description: AI-friendly simplified and aggregated endpoints
  - name: Health
    description: Health check endpoints
