version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: budget_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget_db
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: budget_api
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/budget_db
  #     PORT: 3000
  #     NODE_ENV: production

volumes:
  postgres_data: 