apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-db-pooler-rw
  namespace: hack-for-facts-prod
spec:
  cluster:
    name: postgres-db
  instances: 2
  type: ro
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "200"
      default_pool_size: "25"
      min_pool_size: "5"
      query_wait_timeout: "120"
      server_idle_timeout: "600"
