/**
 * Client-document corpus: the exact GraphQL documents the client sends over
 * the legacy `/graphql` transport, with realistic variables, keyed by
 * sha256(document) + canonical (sorted-keys) variables.
 *
 * File: `tests/golden-master/corpus/client-documents.json`, GENERATED by
 * `scripts/gm/gen-client-corpus.mts` from the client repo (`pnpm gm:corpus`;
 * `pnpm gm:corpus:check` fails when the committed file drifts from the
 * client's current tree). `meta` pins the client commit the entries were
 * derived from.
 * ```json
 * {
 *   "meta": { "generator": "scripts/gm/gen-client-corpus.mts", "clientCommit": "<sha>" },
 *   "entries": [
 *     {
 *       "id": "entity-search-cluj",
 *       "document": "\n  query EntitySearch(...) { ... }\n",
 *       "variables": { "filter": { "search": "Cluj-Napoca" }, "limit": 8 },
 *       "source": "src/lib/api/entities.ts:312-331",
 *       "status": "live",
 *       "variablesSource": "src/lib/api/entities.ts:366-374 (searchEntities)",
 *       "timeoutMs": 120000
 *     }
 *   ]
 * }
 * ```
 *
 * Validation (pure, `validateCorpus`): every entry has an id, a document, an
 * object of variables, a `file:line` source and a status; ids and case keys are
 * unique; the document parses with `graphql`'s `parse`, contains exactly one
 * operation, and every supplied variable is declared while every non-null
 * declared variable without a default is supplied — a typo'd variable name
 * would otherwise produce matching validation errors on BOTH endpoints and
 * pass the replay silently.
 */

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';

import { Type, type Static } from '@sinclair/typebox';
import { Value } from '@sinclair/typebox/value';
import { Kind, parse, type OperationDefinitionNode } from 'graphql';

import { canonicalJsonStringify } from '../../src/common/canonical-json/index.js';

// =============================================================================
// Schema
// =============================================================================

export const CORPUS_STATUSES = ['live', 'dead', 'invalid-today'] as const;
export type CorpusStatus = (typeof CORPUS_STATUSES)[number];

const CorpusEntrySchema = Type.Object(
  {
    id: Type.String({ minLength: 1, pattern: '^[a-z0-9][a-z0-9-]*$' }),
    document: Type.String({ minLength: 1 }),
    variables: Type.Record(Type.String(), Type.Unknown()),
    /** Client `file:line` or `file:start-end` of the document text. */
    source: Type.String({ pattern: '^[^:\\s]+:[0-9]+(-[0-9]+)?$' }),
    status: Type.Union(CORPUS_STATUSES.map((status) => Type.Literal(status))),
    /** Where the variables come from (builder / hook / route), free text. */
    variablesSource: Type.Optional(Type.String({ minLength: 1 })),
    /**
     * Per-case vitest timeout; the big `limit` cases need more than the 30s
     * default. Minimum = two sequential per-side fetch timeouts plus the case
     * margin (cutover.ts `fetchTimeoutForCase`), so a hang is always recorded
     * before vitest kills the case.
     */
    timeoutMs: Type.Optional(Type.Integer({ minimum: 4000 })),
    note: Type.Optional(Type.String()),
  },
  { additionalProperties: false }
);

const CorpusMetaSchema = Type.Object(
  {
    /** Repo-relative path of the generator that wrote the file. */
    generator: Type.String({ minLength: 1 }),
    /** Client commit the documents/variables were derived from (`+dirty` when the tree had local changes). */
    clientCommit: Type.String({ pattern: '^[0-9a-f]{40}(\\+dirty)?$' }),
    /** Client branch at generation time (informational). */
    clientBranch: Type.Optional(Type.String({ minLength: 1 })),
  },
  { additionalProperties: false }
);

const CorpusFileSchema = Type.Object(
  {
    meta: CorpusMetaSchema,
    entries: Type.Array(CorpusEntrySchema, { minItems: 1 }),
  },
  { additionalProperties: false }
);

export type CorpusEntry = Static<typeof CorpusEntrySchema>;
export type CorpusMeta = Static<typeof CorpusMetaSchema>;
export type CorpusFile = Static<typeof CorpusFileSchema>;

export interface CorpusCase extends CorpusEntry {
  /** `<sha256(document)>:<sha256(canonical variables)>` */
  key: string;
  documentHash: string;
  variablesHash: string;
  operationName: string | null;
}

export const DEFAULT_CORPUS_PATH = path.resolve(
  import.meta.dirname,
  'corpus',
  'client-documents.json'
);

// =============================================================================
// Keys
// =============================================================================

export function sha256Hex(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/** Canonical (sorted-keys) JSON of the variables; throws on non-JSON values. */
export function canonicalVariables(variables: Record<string, unknown>): string {
  const result = canonicalJsonStringify(variables);
  if (result.isErr()) {
    throw new CorpusValidationError(`variables are not canonicalizable: ${result.error.message}`);
  }
  return result.value;
}

export function computeCaseKey(
  document: string,
  variables: Record<string, unknown>
): Pick<CorpusCase, 'key' | 'documentHash' | 'variablesHash'> {
  const documentHash = sha256Hex(document);
  const variablesHash = sha256Hex(canonicalVariables(variables));
  return { key: `${documentHash}:${variablesHash}`, documentHash, variablesHash };
}

// =============================================================================
// Validation
// =============================================================================

export class CorpusValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'CorpusValidationError';
  }
}

interface DocumentFacts {
  operationName: string | null;
  declared: Map<string, { required: boolean }>;
}

function inspectDocument(entryId: string, document: string): DocumentFacts {
  let parsed;
  try {
    parsed = parse(document);
  } catch (error) {
    throw new CorpusValidationError(
      `entry "${entryId}": document does not parse: ${(error as Error).message}`
    );
  }

  const operations = parsed.definitions.filter(
    (definition): definition is OperationDefinitionNode =>
      definition.kind === Kind.OPERATION_DEFINITION
  );
  if (operations.length !== 1) {
    throw new CorpusValidationError(
      `entry "${entryId}": expected exactly one operation, found ${String(operations.length)}`
    );
  }
  const operation = operations[0]!;

  const declared = new Map<string, { required: boolean }>();
  for (const variable of operation.variableDefinitions ?? []) {
    const required =
      variable.type.kind === Kind.NON_NULL_TYPE && variable.defaultValue === undefined;
    declared.set(variable.variable.name.value, { required });
  }

  return { operationName: operation.name?.value ?? null, declared };
}

function checkVariables(
  entryId: string,
  variables: Record<string, unknown>,
  facts: DocumentFacts
): void {
  for (const suppliedKey of Object.keys(variables)) {
    if (!facts.declared.has(suppliedKey)) {
      throw new CorpusValidationError(
        `entry "${entryId}": variable "${suppliedKey}" is supplied but not declared by the document`
      );
    }
  }
  for (const [name, { required }] of facts.declared) {
    if (required && (variables[name] === undefined || variables[name] === null)) {
      throw new CorpusValidationError(
        `entry "${entryId}": non-null variable "$${name}" is not supplied`
      );
    }
  }
}

/** Validates an already-parsed corpus document and computes case keys. Pure. */
export function validateCorpus(raw: unknown): CorpusCase[] {
  if (!Value.Check(CorpusFileSchema, raw)) {
    const problems = [...Value.Errors(CorpusFileSchema, raw)]
      .slice(0, 5)
      .map((e) => `${e.path}: ${e.message}`)
      .join('; ');
    throw new CorpusValidationError(`corpus is invalid: ${problems}`);
  }

  const seenIds = new Set<string>();
  const seenKeys = new Map<string, string>();
  const cases: CorpusCase[] = [];

  for (const entry of raw.entries) {
    if (seenIds.has(entry.id)) {
      throw new CorpusValidationError(`duplicate corpus id "${entry.id}"`);
    }
    seenIds.add(entry.id);

    const facts = inspectDocument(entry.id, entry.document);
    checkVariables(entry.id, entry.variables, facts);

    const keys = computeCaseKey(entry.document, entry.variables);
    const previous = seenKeys.get(keys.key);
    if (previous !== undefined) {
      throw new CorpusValidationError(
        `entries "${previous}" and "${entry.id}" have the same document and variables`
      );
    }
    seenKeys.set(keys.key, entry.id);

    cases.push({ ...entry, ...keys, operationName: facts.operationName });
  }

  return cases;
}

export function loadCorpus(filePath: string = DEFAULT_CORPUS_PATH): CorpusCase[] {
  return validateCorpus(readCorpusFile(filePath));
}

/** The raw (validated-shape) corpus file, `meta` included. */
export function readCorpusFile(filePath: string = DEFAULT_CORPUS_PATH): CorpusFile {
  const text = readFileSync(filePath, 'utf8');
  // eslint-disable-next-line no-restricted-syntax -- Test harness corpus file; validated with TypeBox right after
  const raw: unknown = JSON.parse(text);
  if (!Value.Check(CorpusFileSchema, raw)) {
    const problems = [...Value.Errors(CorpusFileSchema, raw)]
      .slice(0, 5)
      .map((e) => `${e.path}: ${e.message}`)
      .join('; ');
    throw new CorpusValidationError(`corpus is invalid: ${problems}`);
  }
  return raw;
}
