import fs from 'node:fs';
import path from 'node:path';

import { PostgreSqlContainer } from '@testcontainers/postgresql';
import pg from 'pg';
import { describe, expect, it } from 'vitest';

import { dockerAvailable } from './setup.js';

const USER_IDENTIFYING_TABLES_LEGACY_SCHEMA = `
CREATE TABLE shortlinks (
  id BIGSERIAL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  user_ids TEXT[] NOT NULL,
  original_url TEXT NOT NULL UNIQUE,
  access_count INTEGER NOT NULL DEFAULT 0,
  last_access_at TIMESTAMPTZ,
  metadata JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE notifications (
  id UUID PRIMARY KEY,
  user_id TEXT NOT NULL,
  entity_cui VARCHAR(20) NULL,
  notification_type VARCHAR(50) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  config JSONB,
  hash TEXT UNIQUE NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE notificationoutbox (
  id UUID PRIMARY KEY,
  user_id TEXT NOT NULL,
  notification_type VARCHAR(50) NOT NULL,
  reference_id TEXT NULL,
  scope_key TEXT NOT NULL,
  delivery_key TEXT UNIQUE NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_attempt_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ
);

CREATE SEQUENCE userinteractions_updated_seq;

CREATE TABLE userinteractions (
  user_id TEXT NOT NULL,
  record_key TEXT NOT NULL,
  record JSONB NOT NULL,
  audit_events JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_seq BIGINT NOT NULL DEFAULT nextval('userinteractions_updated_seq'),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, record_key)
);

CREATE TABLE institutionemailthreads (
  id UUID PRIMARY KEY,
  entity_cui VARCHAR(20) NOT NULL,
  campaign_key TEXT NULL,
  thread_key TEXT NOT NULL,
  phase TEXT NOT NULL,
  last_email_at TIMESTAMPTZ NULL,
  last_reply_at TIMESTAMPTZ NULL,
  next_action_at TIMESTAMPTZ NULL,
  closed_at TIMESTAMPTZ NULL,
  record JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE advancedmapanalyticsmaps (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NULL,
  visibility TEXT NOT NULL DEFAULT 'private',
  public_id TEXT UNIQUE,
  last_snapshot JSONB NULL,
  last_snapshot_id TEXT NULL,
  snapshot_count INT NOT NULL DEFAULT 0,
  public_view_count INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ NULL
);
`;

const ENSURE_CREATED_AT_ON_USER_IDENTIFYING_TABLES_MIGRATION = fs.readFileSync(
  path.join(
    process.cwd(),
    'src/infra/database/user/migrations/202604011300_ensure_created_at_on_user_identifying_tables.sql'
  ),
  'utf-8'
);

interface StartedTestDatabase {
  connectionString: string;
  stop: () => Promise<void>;
}

interface CreatedAtColumnRow {
  table_name: string;
  is_nullable: 'YES' | 'NO';
  column_default: string | null;
}

async function startTestDatabase(): Promise<StartedTestDatabase> {
  const container = await new PostgreSqlContainer('postgres:16-alpine').start();
  return {
    connectionString: container.getConnectionUri(),
    stop: async () => {
      await container.stop();
    },
  };
}

async function withPgClient<T>(
  connectionString: string,
  callback: (client: pg.Client) => Promise<T>
): Promise<T> {
  const client = new pg.Client({ connectionString });
  await client.connect();

  try {
    return await callback(client);
  } finally {
    await client.end();
  }
}

const assertAutoCreatedAtColumns = async (
  client: pg.Client,
  tableNames: readonly string[]
): Promise<void> => {
  const result = await client.query<CreatedAtColumnRow>(
    `
      SELECT table_name, is_nullable, column_default
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = ANY($1::text[])
        AND column_name = 'created_at'
      ORDER BY table_name ASC
    `,
    [tableNames]
  );

  expect(result.rows.map((row) => row.table_name)).toEqual([...tableNames].sort());

  for (const row of result.rows) {
    expect(row.is_nullable).toBe('NO');
    expect(row.column_default).not.toBeNull();
    expect(row.column_default?.toLowerCase()).toContain('now()');
  }
};

describe('user DB created_at coverage for user-identifying tables', () => {
  it('defines autogenerated created_at on all in-scope tables in the current schema', async () => {
    if (!dockerAvailable) {
      return;
    }

    const connectionString = process.env['USER_DATABASE_URL'];
    expect(connectionString).toBeTruthy();
    if (connectionString === undefined || connectionString === '') {
      return;
    }

    await withPgClient(connectionString, async (client) => {
      await assertAutoCreatedAtColumns(client, [
        'advancedmapanalyticsmaps',
        'institutionemailthreads',
        'notifications',
        'notificationsoutbox',
        'shortlinks',
        'userinteractions',
      ]);
    });
  });
});

describe('user-identifying tables created_at migration', () => {
  it('adds created_at with autogenerated timestamps to legacy user-identifying tables', async () => {
    if (!dockerAvailable) {
      return;
    }

    const database = await startTestDatabase();

    try {
      await withPgClient(database.connectionString, async (client) => {
        await client.query('CREATE EXTENSION IF NOT EXISTS pgcrypto');
        await client.query(USER_IDENTIFYING_TABLES_LEGACY_SCHEMA);

        await client.query(
          `
            INSERT INTO shortlinks (code, user_ids, original_url, last_access_at)
            VALUES ('link-1', ARRAY['user-1']::text[], 'https://example.com/a', '2026-04-01T09:15:00.000Z'::timestamptz)
          `
        );

        await client.query(
          `
            INSERT INTO notifications (id, user_id, notification_type, hash, updated_at)
            VALUES (
              '11111111-1111-1111-1111-111111111111'::uuid,
              'user-1',
              'newsletter_entity_monthly',
              'hash-1',
              '2026-04-01T09:20:00.000Z'::timestamptz
            )
          `
        );

        await client.query(
          `
            INSERT INTO notificationoutbox (
              id,
              user_id,
              delivery_key,
              scope_key,
              notification_type,
              status,
              sent_at
            )
            VALUES (
              '22222222-2222-2222-2222-222222222222'::uuid,
              'user-1',
              'delivery-key-1',
              '2026-04',
              'newsletter_entity_monthly',
              'sent',
              '2026-04-01T09:25:00.000Z'::timestamptz
            )
          `
        );

        await client.query(
          `
            INSERT INTO userinteractions (user_id, record_key, record, updated_at)
            VALUES (
              'user-1',
              'record-1',
              '{}'::jsonb,
              '2026-04-01T09:30:00.000Z'::timestamptz
            )
          `
        );

        await client.query(
          `
            INSERT INTO institutionemailthreads (
              id,
              entity_cui,
              thread_key,
              phase,
              record,
              updated_at
            )
            VALUES (
              '33333333-3333-3333-3333-333333333333'::uuid,
              '123',
              'thread-1',
              'awaiting_reply',
              '{}'::jsonb,
              '2026-04-01T09:35:00.000Z'::timestamptz
            )
          `
        );

        await client.query(
          `
            INSERT INTO advancedmapanalyticsmaps (
              id,
              user_id,
              title,
              updated_at
            )
            VALUES (
              'map-1',
              'user-1',
              'Map title',
              '2026-04-01T09:40:00.000Z'::timestamptz
            )
          `
        );

        await client.query(ENSURE_CREATED_AT_ON_USER_IDENTIFYING_TABLES_MIGRATION);

        await assertAutoCreatedAtColumns(client, [
          'advancedmapanalyticsmaps',
          'institutionemailthreads',
          'notifications',
          'notificationoutbox',
          'shortlinks',
          'userinteractions',
        ]);

        const createdAtRows = await client.query<{
          shortlinks_created_at: Date;
          notifications_created_at: Date;
          outbox_created_at: Date;
          userinteractions_created_at: Date;
          threads_created_at: Date;
          maps_created_at: Date;
        }>(
          `
            SELECT
              (SELECT created_at FROM shortlinks WHERE code = 'link-1') AS shortlinks_created_at,
              (
                SELECT created_at
                FROM notifications
                WHERE id = '11111111-1111-1111-1111-111111111111'::uuid
              ) AS notifications_created_at,
              (
                SELECT created_at
                FROM notificationoutbox
                WHERE id = '22222222-2222-2222-2222-222222222222'::uuid
              ) AS outbox_created_at,
              (
                SELECT created_at
                FROM userinteractions
                WHERE user_id = 'user-1' AND record_key = 'record-1'
              ) AS userinteractions_created_at,
              (
                SELECT created_at
                FROM institutionemailthreads
                WHERE id = '33333333-3333-3333-3333-333333333333'::uuid
              ) AS threads_created_at,
              (
                SELECT created_at
                FROM advancedmapanalyticsmaps
                WHERE id = 'map-1'
              ) AS maps_created_at
          `
        );

        expect(createdAtRows.rows).toHaveLength(1);
        expect(createdAtRows.rows[0]?.shortlinks_created_at.toISOString()).toBe(
          '2026-04-01T09:15:00.000Z'
        );
        expect(createdAtRows.rows[0]?.notifications_created_at.toISOString()).toBe(
          '2026-04-01T09:20:00.000Z'
        );
        expect(createdAtRows.rows[0]?.outbox_created_at.toISOString()).toBe(
          '2026-04-01T09:25:00.000Z'
        );
        expect(createdAtRows.rows[0]?.userinteractions_created_at.toISOString()).toBe(
          '2026-04-01T09:30:00.000Z'
        );
        expect(createdAtRows.rows[0]?.threads_created_at.toISOString()).toBe(
          '2026-04-01T09:35:00.000Z'
        );
        expect(createdAtRows.rows[0]?.maps_created_at.toISOString()).toBe(
          '2026-04-01T09:40:00.000Z'
        );
      });
    } finally {
      await database.stop();
    }
  });
});
