---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBhneVMp6jLzDgLkkfqyPLUpVBjGyuV0tlQ1ZZJHf5FF0HFlZThER2dHF17BJBR294/Pll8+smhg0hP5S1JD0n50FtFK81biciW7cF/XPtjPwPW/KMC8ovcmeX9aPuWa3P/ma+qgniMGs4YjDNxwxoXVdOWohil9jT5MiC/QIkqiwmxV857uXSvu/iNya906IDRDddkh8LHXEUcLWpiamyLri9xRjX+S68UQeEsg38I+Fod1WPak37LGwbaHb8yh29tp4bqsXKABowTb+cc45bZvUX4q5tSXCPAhUdcWixxT/B3vxfMT2JCfJsvciMXb3Xu5OwZTVEH13D+uF5K85gnZwNBa7Qj4V9CkHdzNIKKOrHPKehZo5KIligsI8NgWgYq8b7gI56eOP4pVRQ762maBmn7+rbvF44OL4jk7D9ERp62E6DTgXjMXrEzeHvY0twPUMIw1tj6OXwIR+yrDnrP25AuJu80g7vZsONzvUDSaijKbJBe7uNzuAcpgSaF1Xn2tEr8Wxq/RMyyh+hJTuHE4uBKhrHC2J12JZ9sG4VysE/M2uartnCA+ce6aeN5So3G+71l1GMeBH5nTdBA/7s3n/2OI3nMgIMy9OdXKdDnLsG/WVnVAkhHO8fByrmglZL8dttRMbzjDvjcw98GGmbsW/lnY/cKvKebKHkNO//yIZR/XE+zeouOUz8RU0yOZgChIbUeUDrz90tI5pFL4VzstqhiPaLxIPiZbQ4DjESVVg==
    username: AgCo24qlBFLMxu/I54qUTKYrP4bUqxObCubvQhxnxgc+7VP+X2mf3CWT652M8mVevyfb5PiMnd/tZ6lNuTlkITI5P8dth4Wbx62t/XQAfwrtCS5RSxepxRY2kvhkGbe99+587jrgezNXsU+WrKqpQajOU9WyGD1v+10XzDqTl5eOPhFBpK3orm2LADx2JM893eITmwsqwW6oCXh4lQR5oRfy/F7KVxHyLnawnMrIFt0yDg/LN3WR4xeG+c1EZ3AWn5jyd/6Q1XhAxPMdpdkrpQweJBpqiY4pA4qIzLp+cZz4/Y0maI8PbQ2rKeIHPvHAq7SUvAbYp0YeJxGgl3OhtCZIHu5PAmLyM+idF1wXseJmPtI/gOTG3aMyp5P2OvCodjbY3xlaF4FP4IVdSL2OMkRHQ4i446GGL3AAuAAY9PRgGp/v1m0MhjlRDM8PYdd0QldpfkqX+CKQdRiPIlF8IlS1bzk4gOMdeJpRvDRYUo16CuNLOb1WlvmWy9Wts360iqH90UoIwRrE/XZ9pSOfxnnuUQLsH3jY83yJu+NavvLGHcBnw+4RwNkdC0rt2Ov6SuwF86Bd5pwSqAWaVn7ii4CzNA7lgFXCviegIIKEykHW/mCfeRHu8NYHG3E/swJp40QMtbIhRe0on+gEby4vuWNTYbWDC5lPm7rdt4R17U8018CTIuhxvnVkyugmQogecSv2K96W4e4unZsRz/gv8dDsCV87
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
