---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAyBpsaMLJtDsH8iVB9kWjV6v2u4xOOQONSvI0Qs6rtsf60n43pxQpiD4CClzN9wnuP3q3b7RwrX0ygO2gn9Hyf3Ym0L8Z6bLJLGupLVj4yKYgXjT8YmAYX3S3eTV1H5rnXVB7e/RLgjK69y0TCM0ZQGRgk2Yg00d/WoZrntrfusHsS9fFBsFI4jYcFtvOb7+tM7QMWm0fpZ/dN/yPHiaGSHwpeFYx7iDplZ4dup2nNfmoGhCDstKLCN+4CNZlC2uZd2Jjui9hoMzEwZBATbea0Xp4LFZ/a4Px9cP7RoYyf10KJ/1pOwaCrwq1wsa1dBv/GiHLgA+vpPMSMk7Wh7XcOHbeta4AO9GPCel15Fr6Lmhe8hoks+lgznP/p1PXnGeMtHtLAX5TIEhCXOZueBgmXHsXdJJiL+QOWxYJkzUpQXIv6rEBm/cfILGkiCg1tM1KtuqKJu1iIF/DwmMTCZecR5xAvslkcU1ThC4WwVfdFKSL7suZ8Ax0bFpICfDPQguwbs3TclA0sNkCRce27UB+OjYXVV7Z0zDFEWKdsWA3rWDaZ19swS640vW1XXVGoCzOYuBB8xV4C9Rw3a5F+EVVcUvTJy4xQ7fLtLJEEf0scwcuHH+sVgiAxKVdjfh8tq74WKfLeD/HxDPYbYhFRaOfOidNoFs/5/H5c5oC6NyzWNaC+mHiNDYyJ4GzX1vuTdipbZfjrLg4IP1tRaoCj/o7MtYi37C6LxHLSDo7yTiIh+yptPmO3Y1/yTUyiFwN+R2rLILxSvqtoKRXKxAfMiGceksAridXzRjw2pSZAVU1uQwV+bDUfn5puDzKQGvxCsrK5hefzAFoR/UniDfSiSbkCAENLmnyVqPMaW/9H3VpG3AT6a+VWqrwUwXHPUPtEKAAcGZNqIUjUO/sQLB3SXIRVZtrKf7hpCIm+D6LWQuNb66S5JmBenPQXXw==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
