---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bullmq-redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    BULLMQ_REDIS_PASSWORD: AgCwCMS+Ym0m/TqTxnD00vJF8Zjj0PWoKu4cfscb8Hqu6wtXB74ZHesOrLahEE7CU8qMsjY6t7eTOHnXZGSjerV64frBsfNnYcKPRdX/KJP0uQxe4nS9PNXWHMyVjmev3+ZCewAbeJsVgGXJ9NkoGxstiGoCZNqUBDnbV7EoaDUVw4eQnrjE0+2cwc8U8GSpmwpzmtRWzHsxQ8UfbM4l0UA7YbP9Qi3UL+tyYMygu+o73Fz2wzQ1RKWwRnMpREg1SHcvsFsRm0bJhXxFKrl4cOkiO9iVz6aqJwleH+Y6vLfg+hl+UEmFPflVG9KKCdcdluRhF/WnOnCDR8EqgMWWeD/yxlpWNwwPGkq4ujKTlDeU5vobILKIJjqkFIwEsImHNzxRm/A1y8DWeQZX90D79OaPHR02KQZoYT26zP54iYn4YsLkl/rZJ42bkTX40GxMLDICp9dDXH1EuMJtGvFBXY2is9UWo/LYbCj0o3wEIXBmJlhaTQNZVoj4p4Mf1/+X2fPn/2983f6ZmYfIH2iSENC0dRnat/G+jgwLDO2h8IWumqU1oPNrnNZ6p5qYRh9XI0cDX6nk6oT0VRezJzmb/04uki0N6mpPn9dJbEYRWcwmocmKrPJoufDsnfC7FMuGDvW5wVpQoltmcuVURx2ixivi8I5GfpNFUF9IDV7aRqIogMl3WadjllI7Jq30ZZSUiyIOQpslwpKx0lNyQTYYhLOlUzKivOk8hgI3zjAhbs/jZg==
  template:
    metadata:
      name: bullmq-redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
