---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgAq+SSzFw6W7cSQW+n0QfuVlpVtn/HLxFoWsl9BqY7/9ADdbfJxZRTxVodZLhWDjii2w0oE8bse/wZ218z8cSF9Cl/QJiNYRNWRJCstsk4qnibaOSVWoXWfiWTxr67Ly+5v2CtzkdASaCw9YqnpaSl6MePWA5liSQGWmZsvRGc/2R2casXzdApagfPbhmKQ17l2TE5Jy0BkRf3H8W4rkorV5NUK0w8MuZH9miEPoEb64mf95uumyfA6ROiuQ6UMUVIIubIKwRVBsGeGc5nXfgD2N90fVp2Cq4PMUwvK5NitHsJHedeVAoFMke7ccMBg/ILS8scBTs9hLrjEaLN+/kD4bz7BdS9v+DSwwV2ybeXznHuPnLWM5z7EUCcBLZJ1Q4HmAjJkNDRKfop9Dhnx/AS0iC+6MdUzZKJa8p0EA4UUIaJLGguNXsXrJ8MgO7ZUi5NhTPp1HBIJfmP2XjkEXXtSPpnayzLVSjiGxT9ofnv3y9Lz/+dJygofPr1MctK0VtpXVWB2hVzELOdAZ6ZkPkJ9Ek9u1Fay2ebn3RjgDLQ63kWUteoF5eH2sO8pFvyqTEoeTydXbu5uby+VMiZZp/bHo+ruvak8kXopZuffvsB9ICBuBsXG1vXOgDoBzsJcZDVD0ggFLRPNe+X5ob41g9U8JF+sR2Sp1JaduLsJQt7uGqgJMFgoVZKqpYOBPwboH4DdnGKKWrEWr0H5HN0Nk38d0nNsKyuTIJYjzM3NA+pbXA==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
