---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAeJNQGYNatOO2Y61br6UHTtQL7K+DqeMm2lzWThIRiS7rlgPwybJhMH08gLlqp2i0Tpdw07xWUSBIUf3Ie2Hr2rJi3U5EI7lW2hY+9c5hp8CbpXtTkRvwi51ymsLWAQptPsWEbzOYGzDzarf34qG/adR7TijWhbUh0v52LKc07tw4wI6ensZdRl4xJRTZAh7MfliwadDi/v2K2c/LIFz48IjjVW5Z0x+qTxSnDHNfwBsibKlPiQXVPOubsoTa9hfQlbNsCdRwYcsUnakNOSSVIYI2xPyGAO8v6jg/VrNqYH0dxiXWYF4FdH+M7i0QJVKcUPU2Ak6AbU8y2qrc6n4vNK+apGNJc1BUVkTw4xEP/KdjOpQ+MwT9RvjnLxcoYrpPmIh0waTqoq0oZ0wEECYTWcGYn2cHgoOFyEcqTqhzlLlKR5KWo1EOffwjQsvZ1vR/0ITS+iwNM4fJzm1ssXhy9JXDZP33eyOJ8Gh0TSqwKmMG5WmNbC2TaMIv/m3s1trI6ItAZRCjLa2V7+/usftPkQAQj+JniYmOhVRvGzD1jxfRb++O9uB4nQaIdu1QMa/Fsf/NLHYCDDifp/ZGDKvtCjD51ZnxShjSD1H9pTkHSvRpQG0ZIHPGDzxAR2+fF8qkQ2x5xIjl0oSM7nVmBAenbkelpGiGUw2vKUHHKj7DwkNiGXvsxzUtnJtU+2RtlVRiqY8R3Ypm3P3tJF9bJP0wY56/L+/oHwi9YJElP2D1Geg==
    username: AgAMgbJXeKgTyY0mTvd2GcqH5MWVH4i4oQW1RJ32qSO8G6S/SsKDu6oPHiR49Ts95SW5YuD3c7TsZZZyNQxXTiIcfdU+XZ8Gz3w0YTqp4sR+1DHgu4Ps8Yl7H9+h0Af1uImnxpB4iPxE5BTtLaIwCm5Lj6SagRpBBPfjEbdS7WKIn4RmOpHkEh7TJX7n4Fq3waTQAAdIlMhyRluhPqIrh7wZD5q7md2y5gQtqh4Ta0HYBCjK1EPDlpMkl1wntf/al9PPztNuOLhUL/fNN4pdufa5voubQlaMF3XHx+O2yVcsE7gcnEWhYO1mMFqlaqzkV2OebXH/c8TWM7rQE4Q4ci6r2/C5NJI6+HZvBEZntaDgaRIKZr1VTvi1xQsOy4ihAwAt3C1GzKkUFsEZtLJ9oYgJwVJRl/ycMFGZ0MN/wYglQxRseDRVHrLwXzWW9AyHBfaCB6p2Ignsjyvr//dxM7ja3g4LWXNONYa+QPs4E9mlc26VIoeHw34XZFiLnJDnFCCVatWSIzG3Zk+7mlnbyLBxWEYbvfEY6x1Rp4kYr1oZe9hmE5RBkWJPbl9+p80A8FVTaA9EVhLWo0Z1Z9ZxYGrOCWCUL/BrMrz3AcWqk1sp/A0kvXiaEqJZa1ebpeb4KEvrAct0U503m+s9OIABmk5/rwTaub+bTivWeMhQc4RWvYelk9ouhOJMqoAnNdmW/VTZS40ZfkLUsQ50B0qjWcs0e1J1
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
