---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCPv/iikFi/Hg9/apM1J1mmghd8RjMa9a04oJJ7fv0psAOOCBE80aNdC1Hhrs/Uqg3BBuXrVT4UjGuCT8B5n7wA48wvaeZgu9oY4Z89BTwHvl1p/DYaLW/ySVI4uG4tcTP8EKd5vawb0Ob757opZbRHSCMP0J3eC2OzmTHe2UcdnMLBYo+xMMiAyNVsCyBCwLm2H0AQPryKRqQsjG89hZpKXFGY+K7bhuyAf3lZL0qU1yhg1WKBmPkMCOeytlME9YP/KXpy6KKv5rLW/odNnKELIQ5BaOXPmD/JPHZwnMJNRf4Hg+XUMS1AEWRlyXf+mryhhWseMGJ+73z6hmC2c+F7dOVvkqcC90SsFlxUL9lBX8HIJAY0zmf6Htu8bUOgtST9P7V8sXYERzbpAjSL76/mxq9NmQ+ee9s68tCfGHR5AKDt43qVv2R9OBvomfcihbJO7Ve2F5/wEv4/r9uH/9UfohpNlW/3FUF4XLn3PA0Eut/IEdK7/3DT1WONCiQUFZhzZAMIHrMzlW7qVqbwSgfBidvgtv8qi2+wcA8QVWUhTvX3mba126odeMYT73J0YQ8pkhyH6A5R7wIbjb45g6XeuO8C3HRzU1WPbZhdQttjVfG7bD2kkZNev56DnocZ3Fjn3b2ywezGokrAuaDzuCbtlHiRpgqBNV9F7jmtZoH5yn0LdsGmvw5ehQJ90Ob6lyFohA0MYHu0BfyFLSq8alIsqpLYLvuMGdZgpMHBldctMQ==
    username: AgBJgkPYPK8/ZaXLd1XSWdKXDFBVwXO2BrEJ6OqHXJZBQU7uj0vMGJ7r5cwi3kehZ3Hsx260rR5Md1EOLl8eX2MOuYtEj9lb3knsGZhHWuLy2W8r5Y0ztxyVmBtjkVa7r6PusvROSBwRqdCH3CVb6my5DNE2XZiiYjqK7GTwHsNp+JzcCmYDNmy53t5NJS+nhCuvYkvWbDYh5Obf+twTTPuQkT7aFcoiPVTX+KcabE/zHka8w/dLC2BUfIyPBZ2r3D4/1YEGhXMSJOI7JFG9KynP6QzGwuphK17iSS2FYUlIhnJJSHaXl1CoUA1QbZQSjze8NXz5BQUQPWoy3OngW6r2/pvdmc0gXGRUoUdw2RaRNFcDao0cMWRo1ryiwEUNVTIv/fhUXNAY4VpsTXMFnHIkPENCq2UqNr9tEyQYkZ1pQig+Vet0l2PDyo89ZjF8RjcoLuVXRuvOEy97W69lwY5p5U4ybPfWCFTEhXiBijlBoHPlLG21PyIEqhLhmVUer7dGCzhOSijZx+7sprpYINDAOA40Z9JMoxLdsRvMK9fsX746UbrgYYCX65O33miEQk0GzEIIkoY4CQodvs4mfYeMT4tRucFKFCZCkVlJxViFoR7I2lgt7s/P7Wo4lhs4WwzsOinpw0Mcox/GcRsDwrshEsg6Vl1NHQFRH8J0hFjk0co+yqi4+eBNDV5XzaOQPORv3wrHd48gHA3IGXjzoxW0GnsgcOaoUCmn3kmQkA==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
