---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBaBqfkFhmOLIMTFZO8EsKIXUzCvt7wg82UmdVkA57mcTeAwtmP5VchqpR26jlH+PftATqZH5sCxSFzUi/7yVqm/2sr0dJDZf4tf6wzTu9vuzvCrQASaHTqueCKecLjyadAtei9evVnGEK74/rW0qGwynyVMPdpgoTGhMYoU2gaD1s53GJr1HgDif+gRdO7ehoEnmR18+k+gjGDdD6hFjiXn/NynsMgzUsCuRrwwc89wtgg5ej75nRYKJQ3oGd7uStyR+ggt90KbQAtF/vWb02KMk5zqKtNPPVti83oBpGMi4/63GRXhQSaE0whrKBya6AzRZABc9sQ+ggFFCZlRdCqSXtwWs14U2WL10pfSRTtY5uc5AAdbvQmkUDAsj1gZGeCagW8MKehFZDQ2oH7/n+Fvk7WYBuBtynQBEdGvY6qHLDlZzNKya8wMefwCEBjpS7ZolqIxOIc3Bkq0XLMWX/dB95hrdPxEQeHhrKOn4WgUsqxMUSvVCnS7oj9yKJ5a50yzWvjrZSZcogIKu587V29eUebbmwKOzEBSPidg+CBsFHmPWTzXGCc5c9VNb+6W9Zv7HuV5S8lJ3O46erA8irnX9sjy8lDSaKZkQ6B7mCts9lZ4tSsKyp+W5hMt/bqZxOPGo+qfLxPog3uH5T4DZCWsHIVAh92PUUUK3l6IoJJCrPQcZjt7w3edcmZBErdFMar68M0Wk6AuaA8qEkCvNko4rqXBP/Fmy1upMegMbYERQ==
    username: AgB4kD5AMZmYFbTWhJ4yqdphmpGWXZW57DWJe1P92zznoRTRkQdD0zpWmmf+ZmYdMOI6izx9rDJc5fzOciPjzEqKDbnArWRsBrph3hO2yyGKeVNIi5eWH165lmGzx8rhdFNrGW3Ubo3UNju03BQh3AbwT7CZwg9AJAtU54A5ypwG9Fg1GdrzC5uptHJL6pA1SE06ugg0D6ViNnLZbYyYV5CD1RF8MQChNVU5O5zG8h6pyuZgS3xvV+bft1c4Jet/X8hEG0gvOtSFDrJmDZ4WPKjBasjqSbFdIqdLOxIhITfsk71CuNLlPHz/KEP8jVfl7Rggwh++Pipo56cilb5WVFsEbB8QcGZh/zBl3xAiUuk3I5FyQt9fzx1kzP/C46HAa0pxR3NWESb3NbzR4vvTaTcZq5lNv46FyBW3UhmeJllVPSVSjWilySHeY4ILS9Ixq8OVngv8qvId3WIu9wYg2tO0oA84x9EnRnfIKwhFt1u4/HcWb1Gd3fl8olJz49x5nEjPff5D9cnSSTh/WoefAaK0aq8ni95GqEeMNJqVxIaWv3hDBFHSihMv1Wbfmsb7xwZwlT3If5mB/KUIvfCRpjko/RhQjviCdiiwyIhzvIhdBtLusipgusHIrqotRO5xXw4Kn25D1ZOGGrd1Fgm8LbBfBynBONNI5eWXy5fZ+BXbehUn8JrD4oAIEn6mLIfe6+0w7TKIs5R2XYaMKow/6/5UGsOwKWV8XyA=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
