---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBFR1sISNQgs/138GX4JlmzpmkM0lx2dpymOfNdDZhoVtxfzD8EVS1aPzNHJLZjXS9EO7EPgOC00Kbog1+y2Rn4enIwvnouC6sA1jB88lQkt8V/Rr3/7ETCBCKMqMHL7Op0pCC1QRSfI4Ijs5ZZDu8SWXvFFgspY5fGIKUiRMmssz03vHQgiXAL47+I1mGojEJflLi2orVYGx6xaomzM9JAFzpjXrbK9w4H5kxZZ64Rx5I5aZgV8PRk/SkebaAa/dh0UnzVRyksRHKsvap8D7Ph50UbYsUxFigJF3p7Ox4C85Lb/6p5o5tTOUhAUjUCVZy0HY/LhNk5xMDS6XzJF+XUrWSthX7gk2Xbjs+sFC0RGz1Vf09oMPq3NVknoXW96zFMGW7TG95HuX/qCAfe2FfsWUygDPh/WJQxa2VHGiSxo+ScJD83Dl+ktE82r/tBXmpZh1glwqiNZJXBQIAuShBsdCrlTmadtoA9yj5t740dyMK/1JviVtTF+KsrRhqJWSEFz5UIzeJ8B3EkIKvBo8zPuPWZVPyhWDojIR8fQhTnueI/4hOvLOCnwhcSSinMeYLvljkJol4/5/Q9jrBOskYJfTntjddEymG85qtbOtF2l4icoxkUe2MEhx6y1USJg+2372EdTWM5TLYzKnBa57OtVWdEfMO6BaGGQnRHXDHRPYPLjr2ngUrYJALj2Biea9qbsJk5aDF5iP81tKg9p77dfQPjhbXU0Sz+SNAtx5nIMQ==
    username: AgAhhc1nU7NX9jyL871vF4FVF2I3fZobXmQcdtd2CDiahHDZdo6P16kZ+aa6ugxtEDLZBHghrTYMUdWH4u8SHohEN6oZCbpTWkx6D6c5G9mx48Umfffuesk47YXQLFjN3iYgxc4vhZYRTzsgubt6D90FQucS0Aitd4pJEfX1WZf89orhDlTy9aCEIoiz2Jub89B3J/0Whe0NpMnsKnqN/LS86w0CHQUXiICaG65juX2nyOZ2SSDV6fQs13QRIxlqpougjeXspJXvozQEcanj3z8slXWvLu1buGkTb0Ju5jwF6Qlbw+OGv1MBGkOEAy3XpLou/EGpiamA/SnbM7foeo+GfsnZYX6cvS5xXK1l6husC0lBy1V9kKjdgLg66g1nOn9pTjliHJdC1yV1f3AxEVrCzhddEyco7s53r5OYCHbBtD5GSKlE9bPXkjL7ZsjXht/p+JA8cJniHl1zP+JD+/VKPaWpT5dyAUYz7uPuYsoGfnaFai5P5nYKZsV8NvYX3qftlmTzD7Sq8+ktT+Xtb4SGEIBRoefJWN7YxKTYdVjrJ0n1+d3B0yCoCaK5REkLGWqbU098OMEGpxjNd3yllEKpmO+AeldecNLzXRDqjvQj5avkH+NEmK1VXjLS9p3zvrrln+1Ao4nnie4BkM2RU6zLZxr6K2vH8t5o39BE/CdSHNumCU8Xv7+LZGBOebvm+0ythafRl/rgDY/0/WTRatN7SKRCNzhubR8=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
