---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bullmq-redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    BULLMQ_REDIS_PASSWORD: AgBA2q4Mt/B1fPr1CuZpPliMt4CtBLobPw/cX1+XeE+rlj7F0sdu8m3RxRGekviWEqG2JD6iwGw6WizWEMM1CWGjWdg9RB8gu4b8ZwZE7qVqY94O+dBI8fu58vxGlnwag3bN2+sbsEBo7fAgcyFQtRaVXSPUQz6fQSKlZgUHTvTOelNUh2PGnPOz877gHe8TPt0YfjiS+KK2TR43fIcuI3TFXi58d1FVpurF5LXSt+dKXqHPpsCPCfRYeXdo57okrglnuOtv7I5/Sepa/73UgNV49a+knRzd/jE54TUCbwJ3592tFFmoMGpjHakAp/77A2dIdc7cE2mEeek61x596EhqZgPIBV2DlZrrDGdW6Kgr+UTjD1sEfgn4ApiWFyNWQZkTAPdSXrbTuifNpANPynd30cW3lFWGzxEBOXhtwZDwrBYTrlrEXUqVM57L3lzPSfTSs5A009LlqelmjXH9bLCgN+T4jIiOibwH2hdvY1Zqc9kmu7Wl4dSG2iUED5A6L6d1hgNSr01hT+SkUBiRzxE8u4pLkP7L0YMGwX39rhBKIn482k7/GIZXjIIoGNuZsavHhjuSlODbaRhNW1GdaPQbGfhkYOhyswk3tQbdqq41fvQHJK8HxpcISEKShPTHyQVfpVOMkbUwoUwsM3P1OVvh3BYzea8KhV1SVyBpF4XLfJi2QRyy8k46j0wjw0w/ZTWkN3laZUSKEM5/Ay9Mc//6/pXQw8bSiOOM9iufV0Dk0g==
  template:
    metadata:
      name: bullmq-redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
