---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  encryptedData:
    password: AgAqSNJ8Ol3U6EJViQHUTN2LnFSTnc05IeiwUsRgIgN8DnsMO9QjqM3Y+0brSTPOA42f41qK/2933x6D0Loyezg66QzaiMrhxSJ62tzDVeIJymnMSzijbr9SF25X6GLgS0UtRLXYuy001hOmjshppATRbCNDbYqZ4YMlGeon/f2B2uEoBqdcP8n0vQLCMHt2kBhpbgCBDSmOfzZwfbuKwORzVvixbkv9OsHsGf/h+/SlMPmor4Zg9CyQJBVJqne/63Xa1LES9n8uguEqoJhRj7mC98adxqp25nuv09ScK1/pRmu5jcekfRsw6QdoFWb5weAQXFx2QFx3k9VWSN6Zf0JAmiu3aNekfeD72xJgLAZkqH1rtaa0ZfuNa7ennHeZCVwYeadvOq8xpV44m3xkLirC5W3z0nTmrDLvRCZ7BLGXNE5zNr7Wh4oLyW74jO5YoqferGZE9e8BNP9cnh1D0y9knF18BzxMx2U9mvawgtBuV833P792In8Hr3dwLsXJ8eOB62wpok1WpWPv7r7fHGK5w/Sv4MAILmY90HZeDD29esxOpZfGdNIgH/I8Lflh1tBxmKmCHdqf6U+mXe0LfqrQ7qNTppqryHdqPcljuSJE8qhoNUOKcxjalLkCYg128ogHug/3IadnwIGcDpaF6F+colqcVGyKDF+R8yI3X22UR3V4G8vtmL3azbAr5zHKIAUhDjoqbBR6i/kbAmGCsbXOX1H6ot0694AFQPxNq6L3pw==
    username: AgC/Kcg4krX+nog2GHdFWeCW3l5UGRDQPh2q90J0seQ6KtECmN6IOYJHCfl483Sz5Uq3NG1ofOSZ2ZHGdw1s9rKyGdok9alvthu3w3G5HZDr50B8NPEheJpaHD3aVyUvDeLJbNZZcdiO7AnlnRS47caaB1EB431Asmhoirwz/Vr/NBpr6mOXFHjCYgsTltpsP8cxrFfn31n8pRlFGI6cQnxwqN70D9zY4689nXNyWiEW/Znw1IHEDsIDReSRPxhAu4+KMGFd1XUZb9CeZIbc3dLBq36gRyGNkRbs5y4tRWu4IcXzdNIE6Ya66uYyT4bKXBaSRCuoyxLwTjc9g43YunMbjdnHgV1PdhCx/xLFEigzj/tOh/0mBESnYa/IgzIl/M+uHc1mATwqbyuvAaQB3rR9rqfL29jMo+mb6ogom7A/T3g6P4aee0CXgITzwN4UfLfTg+Bq2t/Sgad0hIzFlp/HOdZT41pbUIq0v88qInTo+0Tw+anVCEp7QXUI3Y7c3WY6HhO+8x5HSCIN0Cubvi5kiS1MnU9EX0h6x1duqGxem0HNq8uP5PfBGzO3sHTRmkMStlWg5emiwwOVD2XbgYHTkfiDELnRfpY5iDtybORFDzF1/1UFZW+AFcY0M/nMTXG8WQO5J1xZrE9kBPDoKADO3kQIRQ2COa2rZH6SSg5/V5z/6yR3nMbekpBOldByOhWfK0IW11Jwyq0zOdv+/ghLYaK3koxdxeo=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
