---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgDDPRFoow4/KPw3+dRDt3tdtuT5ud6PKu3Ds250kWG0nsbpE4jc7DVxRjq3if180VU/NANI6OOlhU3SIRwaBkSr7amPut9lSMN29TXGUYlda6Tro402FsxEuixXc2SERpxUKS2Ys7VwpUqpPYqrnDf/XfMk7hXH3hC4QACd/ZrD2ar0PdrIuWV9fXTckWxcdx5X3Dgta8tiPSGVJJS1NpfSS9VwgTbaFBHG+hD+tTJ+1NxHcOj2Lx6OwRg1pL1fbQT4txQGP10jb5TSA9zq2nYvquaMw0KSKBuSOGteUGC6EwaGQwz5JNz0URPAkp3AnM5PzeJTcdl0g176mMISR+jYN2JfPCSNg2AD00cCkIWYdMNJtAqT+h2rX0VmXa4gFgvoEYTeALFYspYYYF/Wjg3kDDgJCCh4jODRiXXQVbwNnG2pfOTJN3hQTcSkT3d8wtH/WSTnnCCoDmUfcWsQhIA3GllkA29ykTs5sAd0pHzDDoGkUgx4N9Beo62HSKJiTdL/EFj7FfoigxmFVHJSCz21yTa4ekdfyr/w9m4Fy7qU8SbhyWQHv42FUSFuwnSwAYlaeZj8w3Hl7KfpfX4cc1VUhOid9qvD4fNdmILVeppGTXm4w7dnbz2FzlPhdvbRXRpZVwjp5UvnNqmfZ2pYVBL82Ih+CcGj+beGJJWqXrMwgAhW30YoO8zhkDsWnYeXnQ+82afq7xZM+Mij9c8gYMsjr5EP5Se8OjMnDTcmottU9w==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
