---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgBkbfOurz45tZcyHxwmmXHeuyfUQ7x6pG+jh8IAXB723f8afOrkDv0qdCIwq4QpMyO+vgSaQigtkoXUETdPSKYORYnndmxti3J/oDd5mgvWArQ0kOfCoLP162kdSqWo621FSaBVvbzXQ4QX8i6W+7cNgeu4kydfpAlcZ60fcdUuF2tsF3e7d4HwquXyefwD6ZHsRfh5308IVLC0r+yspiVpAAc/t3FKSgo3aI9gzUG36I0w7yD72la24wAMDpxwwAeYzcBDxeNoK78o3ywmg6uJQJsm6YI1r/QZB6M7YcdZKtty803SgoAd9PudsaWzVwNjbnShIbha1pCOjG8cR7Yw3Gs2VDEBCedRAYanMvZgiQ+LL5IMpOY28EFT/GFV08CSeTRedq8mSlRa3Ax0WceI76WPS/BrnR6i4vsMxV9niDrcsNc9TjBE3MpulBN/QZJNstqE32gEmwtYWTycrwc6TvCaOvksKiXFsm6PCyoJcK4Um6jnHufyPWH6CSgnN4aUBcqPVC6CCdiCsdIifDKtDBz34wznna2pTQr95rv05p4KLI3TUsaW5ebkzq4WFnR82qAQUTLurmZiXc7Jj22NmYVloVobkdYXQK1/1zMU4n+CCCmo7r1IFKpX/Lkb3XOTPDoIapnCFfWOJocLZXSNVzsU189wJeFKW+nqS7BiJVUcQaPoXLC/KQ6O7n2yS0lJ/3/aZ1MDJaYqltmoEizh/yaGy/RwwCIB3zfompEBBw==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
