---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgALXySkdN3fxj2YWuMivHZAponDqiHb0M38/U6knCKvRm9egmqQIMdkI1r6Y2r5xmWBTrlJFSCQIZJ4ELW9VGEbSS2RlvDBNl19MusuAd/Qq+xmrmDRBcYJRaUj/NXH8FBvRka9NfiLaO7lZaMwgcr6H4JtcC2HPn3/+JQzIbE4L2AH3r4UR8/VbXvwi8EjVTYTj3qh/J0a7BlllRgGxcn4MlDjJsmhhadaMcOBC06Y4f/s6N5Bm3Iy/fD5/mBcum0z2HSCuAj0Qfz85uTPTMBJMS2GYj8ReYtbUz1/DIspG0n+LZdr8d4ko3YRDmllArSMm3Wxv3luVB5JwEDS5kMtMHL4ph6DWJd9Rnm4yaNjVHnKh1jkl4mBy2e5AMrwT110FPkj0oEMx3mCOWXHRxXOcN1lBsSiKGUj8ZZSlMBc+Pm47PLNEmsZ6qkjreKmclFHSz5hMnlnIsTSBG+JeBzpxYgaDp5ADUbyjAPT6koGzi0bTkX+eWurHRqA1DzVdwXgIWnjVll6PPbp6eVHZIK/iFWgEvdCfOMMUl68TvbOrP8QnXssEnk6t5Pd1Z0Q//NY7zbriEbdsfur8EfdSLGcpRl04NT0axPE5xuWBJB7l8epQkw0Tju4IWbYV4oz/9R/N7WA4Lfky0yv/qI42e0Vef5LuguiXVATRfPl6ZIvXeTP+dM/LLNERpE7b7Ay9JGfk0MY9TF4nBocIV+9tJlv12cViliwsZI4P+OkjzXbDw==
    username: AgB1DbSS4O1LiE6a4MEuhAUFLvWQg4OoUTZeyN4yEoeCBn5g6DUGY+w9NpZgVmBcSeVrTf4ba3Mp6YDIEj9NEWvkR1ne6qtnfKUBALblFsYBvX8fUMvz3KtAtWtUVvSYzYfv2qXFzYumqrOmGy7ULkzO8p4ZTAp7k8Y3j7ZFjiMpb+9nXEjgc+88Qc01CibE+tEk7g97xl63NxjPhIqlhy76LCqZOcvybyCMktpTh6XIDqovAh/vkrz6k9zFIBJjpRWW7t9ooHfW5XhoFESDI78pnb5uTYMOwAxhOkb60g4+oGeDu+l4+7C81rXqXPDpYwnLR82XyIX3FcARNrnQSfIIebJ7CtJmVqro9NoDjoR1/fWmIBuTncDQYO2IWOKOAgCo/So7hNEGdV1p4D0xABkFz0YPAGQ+HUzcgM0UiNZEPS/rqrVE1kvXIPv3DOoxuP29izyJUWGI/dAU1ZVffgTw9lIAuAI++1DUW3KNuFiibMKRTMbeCz0TR+Rj3eNCju20OD5rhN5KE4fIoP2RrfEZkSjeiiUSZq1mGQ5QlabXJw9H+fPFNz2RQN4zn/oYY9fITnFcp43JiPDzZfwyc/HTR2qUc9ohkX2WSk1ny8z5hTvKeUq1+50e4znQS81QX+MWohGAZI/h54qd0T03e0EQ03c4M63ovJLMWQowu8G/WaQDb2rp4zB923TgDZqFSOaSvfRfVsmiWgiJB+4B4Lfio9/3ONXUA1JulxylDQ==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
