---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  encryptedData:
    .dockerconfigjson: AgA5z5cHwYrEoL3ZCawvOtDpNk7nR5EwwjE5CjamAv4dO+e1amNtJepzIjsBP/AS9XInR5nHm1xW0yYX/z8Mwyg7XY2N9q70VBITy/W8NFghUwISuBZkvMsqIpfkVlD7CUKhZnkC6HaeJC9aI/ofSUh8ucwCjpVePOX4axbvn+pYpWyyMLfYjVvd3/iYnMb02kqhlk+/Xq6+6/px1f/A4CwHpGz63vpmM7VbZ8vO0gU5VKQ42cR9BRnl+g8jfygWKq37rL5C58a4SHDG5VMAqM49EvgznIRHnd+jFkW2M+TX9Apbl+Y5eslprNLchPCwVahyKH8DOcX1EW6LMHjmYYkuVW0F1JQZYTkhQQTRiXBC6vyfjMB+oeUKNuTTSlSPGcqmZ/CCuXf3e0FzPKBf85b/ACvGAXGwM0n5Idi6d2+6vh6lcFHiMoRX9d3zDFL/VW1rkK3w5th0fa0L1YsOqCbdUUxIjkB65Dmme82A66uKLB3wchsoc2l+gYaeD8lo0BD0TIHBknRxvgd3CGtUDozi1QWsJejWmQwtysZscv8UDz8WNMeCcq7sI69LVVzu7Spb7qKktsfkIf0RlFfneP7JdgcYvwiQr66nuyuYlNqyiSZWRsJ/ktMB4G6AGFpyMxH78s2kppQnYN/UqB3pXfGXG2eW/vqWJSca0vtxZFSJwub/WASOW8yBtIYgL0hyEtYncVgIkUCAKL7+eBUp4NFlFYQbLagp+gwIIxoPJcfad5+JlQvDv4z7E+IFNYjkNSKvuOQwcspCu2tFvqXEitCdQXLA/NuCw8bqlvyj7agD5nXZrOCXp6/4hxi2Wirsl4w9FUZBCrxBWL+I0vMm7yXCmoZditDouqfbIagfcKArpDVsL0cBbCiCXiVAbWfHV/NBkq0okQTYCCRugxEYy1rYu1XSLjc4RuuJiwqWhRJTsc+ibJ6S2BOnxQ==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
