---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBVGLtjNZF3gCqSEm8zjEwsRfZjufyoRKKcjukQn/an53f8vCYzAwIhvDUJ1EzJe2+cQ5SffL4dsvDcfGC9NqaRBDuWTfUqxdG1TIfvQrRcBL3cAb0LGc2rIgA+AlrIbb5OeoqUy9vmVOcpUuEOaq434IC1LiAKfLAWsAhFAYe/NQSkIsT+fab+47mnyQe7JeUMVr7Voh3InLybiLckWhET6zg9kOf/6VtaRyQMRdFhfesQeBcUqTjgOSMYF35zAw4kEdZLeLU9K+yxvSDsQoNGS6peCmm3QJ3kpoFVTXaeEfd3lAekpvrI7L7Ix07PsJb2u5t6E9jLSrKjWM9WoVgoWy9st8uTPit3qBKUAxnBe1jNJgfC9DnbeKghf/69O57AvA3tEz6YnHgBgbcATMD0C9AdRnz7tEVGEJvaq6Hi+vv+Pewc2HLOy4rQCBz+s5a53HqMvIzWQLoARiuQo0kOQKeTF6D8IqHju/GBuusAuUhFoYpDQ3WHF4FklhYD5HFTtZcfDxgLELT5yZkzAEPM9o70hzaXAYVyBAl/Tvfl9NLERfDaIvmhMbRD6L6dsxRhhRy0xUd8YlVse7PFBd/YKTHMyTxVSGNPtEZvrgV159/q5sf4nZPVnjYap5SDMW5vKMMYsxXZccVOHzVLFCgDxvrwYtAjTPnUtUoCE826Lsrt7VB203hzM6uoLZ61ciInGOjRCulz2/Aekzx3tbOQ1GzxYKtvBH/XnbCvFdOEDYAiItCw+0K5zWRC9iVNNFoLLbQNKPLPp+uBlc9z1yK2Fo4lKG7h08lL3hfEZ9BG9/VflP6RqopWdyJB+3HaY1q1dGG6rV45tCWDyReP+saEHJvT1gfFqAjQOzpR/dS0jjkvATXM0FjUWQmMsqyb7F9CgfpAiHYgbUjems77au50BdYQTv+vcdYkbqN59wIixOKAGstE4bCFqg==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
