---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bullmq-redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    BULLMQ_REDIS_PASSWORD: AgCnCS2mI6krtt4wQHLxiZUP7bLVBtoRVSW00Tz4N61B6zhGixCTubdTDxhWoU7/z7PDXmZbDP2udpPuKsQ2o/fwFuduaDbX8gIgx9FISJTDHT1MnoIttLHn8jr+YXTCMbE1bXKFSFgzgsI/CbtKgmm38/0hw7DSFqv+ltYoXj5G0lmisFZY4wLuwUSkKbWjGcV7eH64lcohVchXeJRReK6iHuF9XDVAEIounHj827ivxRvlJrKq8kPluktfNejU/sdyY2lmLIOjKR2USiFaBqaEsdPCV3tzSZGuNtYt7mr0sZvH/E2UjQv9MAKsEaVxoonh3Gv8U0xYznbjYvHLibW1HWsIGsN/Yw98Jd3DqM3tHzzwdvz1Zxe9TuGO/VS7U5l0odCF9Ii+FXTuatBxJcwDEk9z+LR1q/Kbzaer+0HU+sasiThZyoNmMChKUvNMYlMoiFkXPvrrM6Lcq6vVJ8CcBp4m9Hhlg4k4hx8Ef7CuXyvf1BK6yzZYUPKvSXVrQUw5O7tx4bhz2W3JIX0OsbyFRHUzFvl+4E+V17lFSk/0iWimIGJIM6U2GAo5fANW0PldFQkzXOTYEBzcSNCzGDUgS5kVewySdGwpDxziG+VtvualnWpLVXzYVJQ0/F8e5LRhwfedg7Eedfw/jrQzaMi9g+xYXrgtNsFFCeaebKGxQa6kynVyVuo3GK8Ac4IGlim05f6Y9D5XT4ORy17jcP4CumAPXmAGhyCC3OW7wQgD+A==
  template:
    metadata:
      name: bullmq-redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
