---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCBsK5c8D7R7nakPq78HRrdGyVNNYODQPN+htSrz419GZYPyvEapP5A9/lX9IqvrY2A+t+/2qi7UIVPnNv4XkVciy0RYht1J74WZNl6ILyJc2IGjNDoqivrkwuSLfZxcuzpXrnzbGCt6vlvYniNdKfyY9vKHfKmsKBduesyEhVnjctUn22B3maG6T8Ppv9rOp6a4Q5vFBmT/BC952x04SOV7pSRFJ4/GDsHc3oNX8bO/x5aKGkYZgEja0C+QNpjpOmClos5BiVwzTfa5viYDZ9eDJ7aF88aT0huOuT4K0wPUKDImmvqKqgsGy43Qh9eyVi9rwpEe5Tu3sP6ZRNHzWpl2QCtZku4TnIaC2hPUJHO/xPmFqsJpCBV+Wl9O+49t0WYaY6xxRe6jl+w1FkXF1cLtL3FRs+4DThQmyFd2kz9RoP7y/M3no7XwmWEWQN/gTu5M4q66gf33fg7x40weFz9PSifhS5C7LWwjtD99Wr0IKdR4VzqJn5Ib7FtJxqaeKn4JUNtbSJWOtQAM77vXQv/7fiBBt+FvjkKMDqNj1SAhMW5rTOiFaT5wllFQlOJc9hzO1IP4j1/4mEZH2Jp+XVef23304/7rYuvnqIgVxuI9CseOZS45k7R0DMCG2FWMAI2H2aynGvnObBTKmHKMY3v9gmsPxnSJH713gH5P4jeasOli3XbwScffdVutjHLAnfJoTKiX9NuVx4y9lnAmgQpm7w8lbrUGIiucLg1snGphA==
    username: AgAYLgZ6VaYezaFgPYWz8X8/JpwD8WHWMv+3tmHTAd36nw+44mCesveRp/JJgiOcTpzUl6S6xjRK6S74dFLP91C12rl4QqBz2438gCT5Kdccat/LL90ZTBMWC4jXQJ1ELceYCcv8tdRYxQIm56pr/sP8HRM5FkrM19xD/RwVttddpReBPaO0DiTeeAiVKTBlNnThb21RyEuD6fF6XeoNmn/+IOfy6tkvOyMrd/OxuF9sRiRmWZpGqUHKb70DXGQLfbVMmoC24jZmas4ZFTzd5m0gm6Xh+DQ1xrV3qOBTGmwLzqzfo0wD03YyxUmXHioeJA9EK1JxLK7bjdsLaq2DcIH92OdRjh+hl8YoN46IYfwlHNC1PHGtT7InMf0gloBcLbhqv6iY2buJLGf5v7IuwmUWOhu7SmjrbHNMOw8yaJJ79p1M+xYc3uyZiEqYPsSZMZFmtOkrJVrU0/y/kojFG8AKd056dbFzKEiUcNQYYn0n7243Smn8y2RJCvVqLgnHqCYCmE8GhFC0LBjAh1I9RpExwPFWcMXIaVaRZvMjYRVU99juCKeaXJhYGtrb9ZWukOLVUwTSZXzRhqsdTvBHklEWDRG3sn+cnlHb7bQAeMJa2rAwAUQ7b3tYhJYxtAAs9WMsqNxlqKpvaI+Lns8IsLdaWC7Ihik+kpssruTB8jqe+lQ1GSKBgsg2LbSLoB0ZsVFudW5UEeJzCjSXMTtOv2usq63wVV2Tg+ph5qb/7g==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
