---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBKnl0jLNRcfLbtQpoWoNxOFEqUBru221NefhDxI92BdNi74eT5goGxKc8EVy5UIcQC9urwpcb381xdFZfBDNEMufjsUVBCNaqcWjnWAt82T9BJpiO9kuTK5YlkQk2TzRn756Ky6NDG+3UoFU9QHWRd/HmN5w4UPrZc/48ga1JuZmLK3VlWxCb7No4LbN5XjyIKSLcidXYMZlsv1X2d1/rfmwLmcxwR/MLdrwQ7aFYtA/dldVAAcE+2u0XhQozHwqYfV4KyaIqdH3c/xSPrOMSBa5CkLolbnMHXOoUji6EWE6EmNkWcA6L4SyuaUXmmnRpt9MB8vwo+Pk4TECcQPmfZs0pVl6LZtPzee9gX/5PHOkENfvTuMOv5UT16TdFoVs3H5f3y4/FqZX2kdm4NpxV7OSUBAI6z2BBodkwXmXBf3phIilxFrzUKV0zTnft1HyOiQe4MR21Txi93PlNYGrkd8vBbpGD7nnxOoGt4WmzppYONb0y+am+6r1xXLlE2BHuvKH1edq/NRybnYRHqqJ/D5oDToXGlwRSSk5pNNBcu4z7yKLgajt7Z7VzHuMGcUKYDyZRQ+WFCl4jiJybVUX3xHHyj3zVZngDnlAMhIXZ1ayI+aiH81va9sddz1/AGNAoLjTE9PlNodIMghg6GoipflYZ7TOi5jd1aAexCJnq9ShnkCNAsnIRTTCJs8azGQiznhZP8ScjBHyQAj75F06gG9UIXNUXtorY3D0EEjNs/JA==
    username: AgBIOWnatPuuUAfafElfz+1TAreJe5oSbvnwR4Q+70lhR4nsfuzLbZqH9G2Et/vmBZoD7ccsq9Y7u+zO0SkpOMic1XoigkSjyTnWzhUxS+nv6nu+n12lA45mI0TxmFOfYPqvRwPCq7D+swN+8wyBkofvLGYwc9tKmEoz1KNNwzH7vsEFJbo8+kitPr3Wh/+V5toEOVjGBlnTYc/9rRC5VcFxmChvtLYTYVBsT9lG72nNroQnHBjSCBpQ0P7vRR2YQk89tWCYD8UwAFsnLgGRElQQiPLAmxuyFX3UbO4zNaj0N9bInozTigiDUJe18H5gLQI+jP0epYHsX1Uz5AGusdmD7AEp1ovAHcsem0Ybwb9jcATJiTS22ZENUrlPi0nF484PtFTI18HhcUZfeQ/RMkqaKhAiByGgXR1FOb/cOMM9+WE1Ece7fxBSgbuO2bhiD1lVKitqz9GjXR7SgmZU33Gtjvdf1bT44pnpGluuTDskGOKbWyHP0nVPb/uVKL7AioIT4aPlyRS4WtUIKnVqwSGWz6GuVFCbTYlMI5Kjv2Smq00xEhtGxRbBMPo7C0p/yfT/k4T7oXR7bMyCj4PtQ7dHF310cUtbIeFtPTxxsJ6R3pSploCtDOVmmNIvj1wkzQsil02GgDBMrQb3lwTAlyk5pcH+d/qMfEBEedWRBvOu0Z6d34qHO0OsUxl3A1sV0r1Tj1nWexJGjLAD0yltC6NMLu/K
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
