#!/usr/bin/env bash
# Generate the redesign PROD connection env from the live prod-namespace secrets,
# SECRET-SAFELY: credentials are fetched on griffin and written straight to a
# gitignored file — never printed to stdout / the terminal / agent context.
#
# Output: <repo>/.claude/redesign-prod.env  (under gitignored .claude/, chmod 600)
# Points at the LOCAL tunnels from tunnels.sh (run that first).
set -euo pipefail

NS=transparenta-eu-etl-prod
DB_PORT=${DB_PORT:-55432}
MEILI_PORT=${MEILI_PORT:-57700}
OS_PORT=${OS_PORT:-59200}
REPO_ROOT="$(git rev-parse --show-toplevel)"
OUT="$REPO_ROOT/.claude/redesign-prod.env"
# Separate file for libpq PG* vars (psql tooling). Kept OUT of the app env because
# `pnpm dev` loads redesign-prod.env into the legacy server process, and an ambient
# PGSSLMODE=require would force SSL onto the plain phoenix-dev DB forwards.
OUT_PSQL="$REPO_ROOT/.claude/redesign-psql.env"

# Fetch user / password / meili-key on griffin; consumed by `read` (never displayed).
read -r U P MK < <(ssh -o ConnectTimeout=15 griffin "
  printf '%s %s %s\n' \
   \"\$(kubectl get secret transparenta-prod-postgres-credentials -n $NS -o jsonpath='{.data.username}'|base64 -d)\" \
   \"\$(kubectl get secret transparenta-prod-postgres-credentials -n $NS -o jsonpath='{.data.password}'|base64 -d)\" \
   \"\$(kubectl get secret transparenta-eu-etl-meilisearch-master-key -n $NS -o jsonpath='{.data.MEILI_MASTER_KEY}'|base64 -d)\"
")
[ -n "$U" ] && [ -n "$P" ] || { echo "ERROR: failed to fetch prod DB credentials"; exit 1; }

# URL-encode user/password for the DATABASE_URL (password may contain +,/,= etc.)
enc() { URLENC_IN="$1" python3 -c 'import os,urllib.parse;print(urllib.parse.quote(os.environ["URLENC_IN"],safe=""))'; }
UENC="$(enc "$U")"; PENC="$(enc "$P")"

mkdir -p "$(dirname "$OUT")"
umask 077
cat > "$OUT" <<EOF
# GENERATED by scripts/redesign/gen-prod-env.sh — DO NOT COMMIT.
# prod-namespace transparenta_prod over local tunnels (read-only serving).
PROD_DATABASE_URL=postgresql://$UENC:$PENC@localhost:$DB_PORT/transparenta_prod?sslmode=require
PROD_MEILI_HOST=http://localhost:$MEILI_PORT
PROD_MEILI_API_KEY=$MK
PROD_OPENSEARCH_URL=http://localhost:$OS_PORT
# Mounts the redesign GraphQL/MCP surface on the legacy port when this env is
# loaded by \`pnpm dev\`. Dev-only — deployed legacy servers never load this file.
REDESIGN_SURFACE_ENABLED=true
EOF
chmod 600 "$OUT"

# libpq PG* vars for psql tooling — SEPARATE file (never loaded by the app).
cat > "$OUT_PSQL" <<EOF
# GENERATED by scripts/redesign/gen-prod-env.sh — DO NOT COMMIT.
# libpq vars for psql into griffin prod. Source ONLY for tooling, never the app:
#   set -a; source .claude/redesign-psql.env; set +a; psql -c 'select 1'
PGHOST=localhost
PGPORT=$DB_PORT
PGDATABASE=transparenta_prod
PGUSER=$U
PGPASSWORD=$P
PGSSLMODE=require
EOF
chmod 600 "$OUT_PSQL"

echo "wrote $OUT and $OUT_PSQL"
echo "app keys:  $(grep -v '^#' "$OUT" | sed -E 's/=.*//' | tr '\n' ' ')"
echo "psql keys: $(grep -v '^#' "$OUT_PSQL" | sed -E 's/=.*//' | tr '\n' ' ')"
