#!/usr/bin/env bash
# Compatibility launcher after the serving-path move to Chronos.
#
# Production Postgres, Meilisearch, and OpenSearch now use direct private
# Tailscale endpoints generated by gen-prod-env.sh. Only Phoenix development
# database and Redis services still need local kubectl port-forwards.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

echo "production redesign services use direct Chronos Tailscale endpoints"
exec "$REPO_ROOT/scripts/dev-db-forward.sh" --tmux
