---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAmKe+/v1wmYZ3rdnu+lcR8h8Wz+d8L+5BkM2NYeWtXLp1aFrIdG0goAvsrGCzXFtaiKYjEDO3zeH242eFlBtz6OEHH9y4cA0AKQmVku9L2T85I7ZnZesLzrb01m64rw8hsVCUMufNuc9z2n3vvFNZo31j9gAWqwuRJgEY2MxgE5LyO9SuJgfR+s9yXhoreZIYHvn8x3TYKqJi2y5kXRBCJ3UH5FJ0P5/IupWtm140vpipuFfSChmDuiyPiWfDHEVl017VhJ8wSGh0NtBloKs0BfVHHN/lQH+FhxbEOavttQK4/hGh0e5djWee6NsE9dALbAq14o9B5/dDdQImHXajNU2PNWKajqKdGhdLdz1QmBmsuSiibeIVXohvXEH1xq7yNptc51S1mF1u7Ohq7rroPOYO3SgX3UHuFOUIH2vXcUbdgZJ9yEi9rBWq1sBHSQTFPw0S8cAOHCoH65yx8UYOcVZ8eTkMXHvuOgzbZZ7HlB7d7RgxaAdCHPB2l1odKFsy3loizL9jTAOJkUfAeaKUXgREqUu3t6WChecWmvRW1l1JBpBIBoLSoUJoTe7Bv4LpNqRU9pCbnKTyVyfhsg8UZy1gV82T6C8PzGcTeVSg3aoKxVwMgjQSMXaA+dKmydhhJhIGqOHzANl76SoKMF7hjI9/Ghp0I5L742lN37SRub5jBmoaUy7k41Q1vV0BNQGa5crngMs3bAbsY4RcYhG9qnZ5/U/EleVCrI0pRiVayFg==
    username: AgC6DJ0G1Y38QvT3XvFMR2dDby2+EwQQZyv6iINWphptZmwwYikczLQDbEPUePocWcoxVMtW5hf2hoigPgH1NEOtZHoqNOutweILi1l8PzYIFNskXa7AJE44mRF8Sw5wxi9j5OSDgeJcirpCy9fYxdi6ffWy6WTbfEjpWfZuNp1kNH6uXBhgNuAb7hcIUd6UReRpMikir0dYBx0Ua880ynmYVZmKy8H9HayfL60p203T8CQs1QKJoiNPL90kww3nVHSPPidMzMiSvgfdoDA9azk12tzviiUbwwVoh3yHLPRSpGOWCFMpS6wmhkk7SRmrfTCDYQprL0FBaD3Yya8drvN4ijF+q4EIto2n8jmEQh7+8yfzyQQyas9/A+vd4wLL+zsqCJhgq24zSRgEhWirK5cx/w/jEl8eeD1ZzPbRPLX4Fcd4LIWpdNlMHJiRAiQKBWdQJCNJv76ETq3JuOkOjRQU98iCKn2O1IADhvnUwEY4QbCEowDKSO9jL5cYnV3a5PCMV3qHOJoJHCUUWXI/C0ZzeY8r8oUeiV0Iic07WU7ydn7AKKhvmfadLu1kdq2NEgHuG30f4KvA2K4ArxY07tX107lFWEetoUOFHq0mwbDP+G5gVWHUS922Mmub2t/AuWKFmgGtgj6TenbJLprx4aspKnUphSOLF+dbQ6DUvbEVpcPm0hcbeKCeCTbZrJy/+xaLHyWCyCZeZ3JXDj5eFzUB1f9nrWMU79vc+ccOxQ==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
