---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgADElnSj80TbSTucmg7zYMnp3UISBuFtxRYKQXYJ/RMF44TostqdyaWbuAC65nPeDj5zHpaHbl1XXEMibh7wDYvE6Jm4jLOUNxOa8sK8PwpA2zsQhr/WpdNLf8rwH/uiyBRDtyBvWsFtqSfvPYo1o5W/ycR787IjNIKm9qj29L4ywWFIMy2Ny9whTYJ7BkxECjS+FWGpCVRBfKYqNKWS+eBrH1l7wJUG/iOOtv9u2qk2PXXibdudGuo1SWMfO4D2khoz6O0fpH2MSCTMQjriO5fbXz1ICtNV6JqoImysqfaHEKFBitJb0/MdQKiVDNqQqeD3h5uieJCB8cXBGZ3b+LZe0q2zA8S3rtRiOaa8WBvnOyFEdbynT2ZA7qjduImzwsMQXiNQRex15a5vgKVWZJMIVRnOpDby4xP4JTZ7XJoeafCETeypka+U5TlTOIG0a7UyxsG4dCDYWXVg9CHyjb51byyr5PYLNYeQDvE/3dSNGXZIvuagAJ9Vn6lUbyMW/B/trEmW7y9VG7ZBnU77uQSgLA/2PMYRDVQI/tU6T3XEa+8wuAtFtEbxjJscKvvj4RsGz2vIdpSi4Ady0dv3nYiztsboVjtNsq3q0q4/Jf6mBxHG4rq2Pmes/S06t44rUySD66RfdU4fOOofd9tzCw3hsBHdPb2BRcDryvoPFIWzSDLXjplMOweF9B+e3OPq42ljNBqlCfzqXqBvzPSr3dFXbFGJwfomXnHYcgvh8h2hA==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
