---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBWmjKzlywEg1xpk+H1IVXddtEJI/5hJxto9yxScUewBFuMbAPfPEJ8UbAfsWtnDCO1DgRbnhIxFyJzqRDq9Oid1gCTekaGU0a3ln2c5sRUOjRdT8c/i2T909ylUaF7tZWiDijSs5gtJCEQA7dLKTos0jO6FJS294XKcD/QclEe/W3+HhQwmE5cAtbTguHzp83W2+KszZsIZvKNfp4VHNvkphouwj7uhoGVD2abqLUTzAEVvNmN4N26Il2H7qSHEtsrQciVzJwikUAI2gZv9QkEye2D4cgImVBYvlmWKii+yPFccu376oxh/0jk/WVnbIoT8q1e8G404R/lvoEXFgN90j4yW/9GzOUTK+cIeLdrT2XHwpON3HlxZSOKVrqMMwyFlayN8FQEej6Eu1suQQCzI4Kvt0ETlbDuSythBi3YD2KpTD4IKmtAqfUK3GNLnE6M41TSM2ONfnfpL7eMVvdqWS9w4xX9TAv71u0Xsj30sjIIW/cp4H81MJRTiRZ1yPKB/kw1fnCorcQG8b/yexXvbXUWpuQ8pzt2nDoUJjtI0nnfk/LY9RFYF1YXqQszJVry3o2mvnltlrC1bkm2/vWOjjMmmZQx6ffDmhEUja163bYFc54wVYgJTTtkMPTVaznQXzlLx6M7+i7lGAeI4oaof9wK7nt2BfyBYd708MY1v9s1Nyr+e5nDXChQuxag+VKwQJ/9t4FO2pBBKmNjWLOXf2WdipxsixYG3Aocydh6CA==
    username: AgCeCw2VPh7q1HZyGKFaDd2W8nqE5g9WNV7IlmMr7y7U3sBxX3swJXItLjnzlZvQi1m5xdRWWnw5vF6Qjm1e2KBN2rAuHJI6l8x5tcDMVZOA0hrYALvzebshDG4yh+Tt0V3a5UwUeXE0a3vwJZipQ99pxbfde90b+9KIpOERblqlrhPk46mVyhu5+nUx7TzLKhVVHlHfi17SYbGWb71n2VuvyVdKs2RNwcJvlSVcnK5kNFBeeLkIX6ACG2nF3vmy1OoYvqRRKWs9OdBnqBRuL2F7yoZPwc+Zn2GnZIqBHI72H+j/eJ4j62J83oUXHtEOrksUhxISLkIJ7rRyUEDCTci5G1Upxy1E8dJ+Pwu4chG9eNbDHW9ubUE9e4LHrscDog+dVmFzsSyvAQkStHWY3iYAfrqWKw5LymwMYvBgBYobXB4NtkhVltWCL64I6eK85w4RQjAPRAUbiGuXBtGCFAQ4OZxYz7TsFgqnbC7JmSwjO891YnGiRcAv4pAPCHPk9/F/6vlOw1WIycTBnlSPegIY65s/ioTyAeoNqCXeyUwUUbkgwQsjYgswD5HtVRF5C5AqbJ1moKn+y0m9FZz57YEkP6GejfJHPggf5Nh3V2ggXV6c5oETDoy3gKnEU3Q7Dob8FsEIJBM28OEagBH2JpGSNFQBfqS0cUi4FNRHeleNxWopEDEOJIoyRs+3ZTbJ0QZsI1XAtg8eHyfjZZ86nVfBA9RfpPcpNGo=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
