---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAApMMzOcbt+XH396GaBEzy4CKdnadB3oexRyc5XrQvU5fV41gRAgi7kzN2HYOfezQ5Tgv/kh7a/OLpUPa09ORFmA8PSCjp5DM9qs/Ds46JgebNNhDAP6oE7IabXXWAHCDvXMb+QHY2CbmuJvKxA6mKqRdcLX5jYUiXIROMBpLKcuEH8rGFkPxMELkp6Oe/xisrcWMrC4FP6ZwpOc+lN1ahIc+e18Phw/QKAH0j92LZzhMBjxzOaJ15aGZZXqmSCGUWWToikRm21CAXat1XrKySeJsxqStAVZAbYNTLgKaD81UbrYkCMCRDTMpWQlEr31/7opOou7q/JjAIaNxJygVLiohlAieZqYuZUp+4YjkhgmUoJnlawuYangGyPZUNgKRRrubf56WK0IhUI13Q0FGvpXClW++8zZr2YVxdI67rbAiZi3rD6/nKwiH+16qeQ5hTvNLXN4pxIWgtgCtpIVPsPgTRb/VegRDnJw7qeKrgl/rn86ZC2CfD1kf84uJE7uL7fpM7EffGB5TXYncKxXD3sIWs4Gs8OAKYf3kgbohRIaiMArmgQYxj/AjQqH/amq5G+w/ifSsAg1aiMRwTU1NAm/xkJstctxLn4PC9L1qLcV+Qfs6sXJ/RToLbpjVP0YKjbf5mHsMHY0uc7Q5PN8Bpfj2w7TDRX7r9qzH9vps/M9oAp8SwfpGzaY7msWomV12tmKvE4gcxkNq/EASuqQh8W0e7w1xOgPs1ZTCb5YCh8w==
    username: AgBkGqYdLTXwfsAPZkAXLfhDSbjUOSFGtFFipa//VKRDnb7jG2ENrha0xPzFHKqoVhQSZ5nD3A/obYHDVKS5mcqQrxPGpvNtNKlC1gmt3Ovpzl2oxgFSJ8XxSZgn/SRv729z0UDYeQBS6uxNr+drdy9YiWjMWKX5eRyiCbryykZ/9bBT/kUtfol2ry+AtOZLjMUbA5w5ylMlJWzAc8O3cHiMjbRpObaZo8jjyJHjydaH0oafgb8giAG23N3ws1Zg1h0mT6lowvcj7DBuLhLyvjp4JvjC4U2SxLmdVXuXGDe3Jm5IeLXHOfHq/kL3sVHXtbDeWCYZYiuWVaIzMOBHdl8VD9xTTUoEuCylIwSgInAnSwIA/9speEWt74VKf7oPBId5ioNw1k2M3E+llextg0bfjHm363PXScGCubFo8uP2DQS3NjTk+Pa9GxRu2P9pczifdP8ehxAnwxqht5L/US1F/2WVidFf23EkTak3Vbahh1odTFlHt1bbUNz2GgDeTLEHc9QBtTCyWS9Xxann6jgXDoRY3MvaP3xbJZZjuC4p4sgDMFnnaiSWys0vNxYTban0fI2+WmaCmFjP6coVRqHuXY2ROQNb9JeBAf4QxUpsThftDzBDdpcjEFUVwN3FqwyKabj/i4bSWDdo3ZvJnUim5TlPTeUCeezmuUxR92OwSbKWNtR5dyoD3F+PY2L1AYG6bBX0gpeqZPMsrWOQ+W4/DQGebvklyvM=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
