---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgDAECqDcar/tE/eXBAn9DVcDTDOw1S/oTJEYNmn50jHzMeWH2AZ5zchvL+RdH+/IxxPx5CMsZhd7XlRydxWMLGBMAQNAURwWGFbwiPFyfMtS7RZoqvf5hVq5LfvKkuBLpD4k5xA4Ryfjg033su0+bHSGSOEDZkYyESNua8xu0/Cmnaj9E4a2RH1WWYzIqr/vjoa+fL5lg9x350Mx/pSKea+dLUdPv3LaWqksqwDEYlMqr5Iqvx5r7TsNqK2J6ArqsnUGOknWlsuArsmJg/NOV45g9b7sJaxywcz9UWZRg4cK3C3Mc7/HZF/YrUkkY3ps1hOtuq1lm7DzARCVi3sqQ5d8TgYfOFqI3Txtf/bpxEXzrN6tGXqlxx421KF4ekkyS9z+mccEugU+4VFkr0BTnFs/iN1oPCkAz7oJUIKUETts65PWbm1M8vVHTKAibohEWiQr608hiAgsxLCR5QSXmgEV0uOexYXwbAvZEqLcNDyt13pnNOnRVZ0AhZo5FFEVmr78KC7vCKBY8avR5tKi3hH/r38gbOS4UwODxu22R6DCjETsDsI56NOd3/B9R4lq5w76rt29ugW0sKzEpTuOrlP5puE0AKUokuvBXLEIiHwm3mqM2wPZDrhgPb9LFoSLfFWK/yaq44J7thnXNkUpEG0c5sa+5atEXKujWWIFN4q6GnyeX1W9It9kD3h7BoBRZPzBYiP6kpg6BIUvCDRF4gzuglfJS2AITx3Zpz9FEALXw==
    username: AgCIjpitK36af8ypDOlT8jF8MHVII1lazpyV1HqwNk2elDst9kUiKdYfJ6edF3t75WCPHsU7SAeRvinfjBI2+qpsDC1UxgX4ho3e2Cm48Pc+EFpidWTJwAGiCnZmOr5KFtD6Q1wpfvIGcOI01/1uAB8b1l3V2XNEUkXt61OzD/jlT/Wx7tRH6Y1/NfViZkg4NOEousNA4t1FtKH34gpra+rk/oi1sdonRFDaswl2f3loIeliPskrrGnU0xKnaVD3RMy5z+CNb1jzv2GKpoqFxyKCqUu95gGLAcaIkkfp1EWPJ7R7b9WUGy7I5VIBDrEDXZ5yb3kG86zHtEJEvx0N+cs9tZh/tMykdF0SOj5fYjtQriwCUQOn0BJn9MejC+R5mHvvmlE3us6aUKMrFg4unHW951hLGDTD7aqqujSygjslWe7QM4pxoyIVOG/yoBQBsDmRu275ykObh5SvxJXYPuYzLFMdRb6VUpJfvqVV94R+1anv170TPMLz0WlVb6LedsvOgN9T9cxduTwc1EVkSNR7VVsM1sUx2ivQV27UO5r7tewcfCFwxJApx71W0kKa83sckjxy+0N1qA9uyHAEIxPaxO13M4kRHEI6sWYiLVGlfV3S9gp/Z5DMmHCazH3qgAaFjSBDPkRYLUx1q2LLxKj7EMcsf0AcEqXBEmVBZ92NMGqAWzsTEGl4UBOOM1RtGRer333+8j16MIZmIjage22Q1hyo
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
