---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgAiSecbDkb/QH9tafTrMeVI9ssa/pDr3gottKMJ411sBcgdhPa+vgQiyS/D/6c4fYC1c4JirA8ykn+YfndXTM2ag1Iyepme83LTy5HZSmb2Tatt4GJP0eIRQmUSXre4tiH9HC1xtNlgfGCwfg6aSn39DxZTeIhKMOqEtCyfktrPUctWsQuTJ1ycnx0y8N2uod5FvcDVnIl6B5gF1LfB/Z9rHIYQ51tmoz5r6WJ766iaLc8BEKp8T7zsL/aA6T4jM1ZShxcKODfOu6ngy4Z6t8uuoBZ3/rvjwp1ZzIBOk2TCMuTQoCSvreoEGC0ErsuoF4b9RVz4puwvh5GjlwYwOuH0Db99BoknuHMR/rtGDTBpC9qZhb2zMblf+TfzOUMTfyIh+X9rxTP8N3Ud4FGfG2zWK/KAdie1Nv/oyKYBYnlfGOyBB8Ndkf+L6X95JGWIbr3hH7JNSD4RsgcTNmSEbUTWcLvZ7dA7vcvl83lvumfCM/wn/E8Oy/2uFh9OdrFiVuu8DmM9xJ2/CJ3Iynp/XeACY+IkDX9yZxrovqphd99m5vltySMYnc5kgQJNEeB40kZkTrATTpJczKxMnBeHXTslDkQfMcV9gMuTZbOUmZAvf6YHBw0+vTjZwsAej9xEutWhaRbW0hGMtCt0JEvYq4q0dC7Y+NOirHykjpnOawVD5jyhh9OCFqd+7Z0llpMFHg7/FyrBHTmatdIRyUj1d7+ETLBJjPPgbs9Q0OQ38bjv+w==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
