---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCBWOhJnxzBKtCv4AJFx2Cn51E573xBtB8TJMfgQwilcEueYLy1eBid1U1meIQ7OtUChZtX0PG0Pf4PttXEnJ/TURas6QGhvAYZ5htuQqYsgIMlwSH6mXAsHZZqoQ8wafQ7OmYxJFnqWGQOdlwpWKu/An9kXs8l8oqqaJsgdmuLC+eykDS+9mG5saO8M4Ytie6z1ag1RUtmFh/MOCAElbgxGUftFH/hL2QWTK8IPGQyOd2pYof9yWaxysD3dBWkolpLVuro2EtkeYwD8TReASkuKrzUYAuIVBtKwds3c46+H2eGGy8Sdi3y8wW3r+EIvg+A+k27+MbTfPuRgP3BRFa81eQuwan/iHCuhwTi2TgyHmAaepRen4OGMzlJhoyl9MZs9R3zqyPVdx2CzzMUWkVngeV/TSNZq6RSFMH4EyWvFRkZouSGMjhjC6gU1+50oy2wYtwhpxLzJY5+V6Y+huu65OHO1KpIO2ryVdyQo+i1pP2y3wLxnLDRUiBG+pz4+qVw0McGwBPvVVebxIcfHkFBs3eFZBp5jDpuN9oLcI3vk/bRgSyTr6xTQ95CAc7gtnsyfRHKM4wYckW7hIoW1Ou9cC1j76Jx4ARQ826Sr2NDNHv6PcNAH4UUCMTfYUBX2llizK3qDddGnq7IUBY6lmmKYlyHCwyxLBCok1juhsv2hbCG88l+SqA7+qE8F5zFRjibkkHKP9mC9PfnWD2Igp6t3aDbREB1cyXHy/OJqwpqvA==
    username: AgC0sUQrlzNQMap96YKqXVsDnaRSCqxrrbaiRbz488YzsHHVwTsyBoXmlPSjn6sJF5VyKftI/LnKhdR7usMI/imHdHd8cZ02K3q3ulq9pKFtlbs+g/40g6JbcXHZ1kcDvP3hM63eARD7dDIWVnksRpN04MtMBiYPVaL635ZXxxCvILBgEz4dpM0kIJ4lUFCSVklEUD4SfRVBymobdTPQUl+fGKtlggYOxBbxzQIriEihAgnbqBbJKlY0rMntU4TSjnvXAGhnSjNgsmEM/ul4jIRfQtgqsZqINYgsynNQf+tZiNTwYyQlpdeSVsYrrcXmQlY1ixlG1EggEvFHNAYAL5a84pgGMZ441s9XM5GIaSgdBhoRteLLvq2pH7nyiVeEC5RY3yAG0grSmieROlZlJdE2OUbB4xz8gb50LhQ38uo8JpbEmyBmHAIroba7V8HWumLQYBh5rBKqZBONRPcOMvGSeC3nZRtXRAG2WyMc5SDEKawzx7cVoinFkb+QhwW6rF5ubN//4l52vCxXNs6goER8VqE/AG4Tl/IwitBlzITTTQTP3AeJQRH3AOBYjIojqzHRNULGeLdnG8OsYIvhmwPtrq3ghWO7FwAqUynM9O+cujgrtdnbhuO8DNPc1n0cwOTzcasQMfc7kQkT3P7OSAjVl7QGGS030S6var2Lih14sGQui1miZa6tnqu3mUxz0wHoH1RWrkMNjTl0bpCXZ1KJXU9XFhuS+EUNR6OABw==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
