---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgDB4klqV3WonZqqQslPyabzEe0SDRwB3jY+NrQkX9tWwvmjdgA3s7Cx5Ggi6ftpDQhGskEot4RMkPjkMsvF1yxXuwIFggreFSa5ZTQi8iPJdhPR/0hGYZs075BHGOYyVIlXWasF19fqlOqxNKM47Xq/cM92OkZxp9SFeAGFmL4kk+zBK3ACVa/rsicIvzZ0mPrHqwP7QJBpJim/dI+jKaWINNRPa42i/lgPN2tHVyGtTqRJLaOCwGQ96DlIP5Wzl3avUUj+/MSXWz64Sk2KCJgl5JmtwMxUac9GnGDOD/3jSQ5iziRF33r5ZMsllJ0djMBYpcDg9QbCpMj5YC/cuTQM2ielriAgVOMv5cmV5CmzBkCsEfts0b0aW9oFTAa4X0RmrZirCUbh4pY4wswOq50uXBx/a3kZAF0EHKLy9D5eE+hdscH9Zlxp7cUx+lYzlyzeDAte3oRQRjh9dLkNUkFzOgaYJdu5DdBq0Sf2ZaYfmTWl8cL9qAYWuplKZ3fjz6Yki4/bMnWEym2kfXPylk7m57nuxg1aqU7MDZOVO9a3MCKwDZSQI7Aoo1qdXTCzDWllFTKrBkygrWZtomBLDYPLnLab+L68Mkny8s7ARKtCPvcqofVid/X/L53iuxH++QRiVYK0hUsPleAFsKlBujC/GcNC81GWWBEw6YtNandYbCCW4STzdv05M8ytRpCqmmiyzH6oJENgYQUo/I05l49tEV1r0tB0mCv9ShONx817j+Fmmo/gOGAIigc0j28LVwYnKUXXIrNmRNBoSKgeH+P/Z+c6949t/Yu6Jrr600LiZ8mTmLxluVhcB6K8FENtV4VpkOoEzieoSyse5ptLZYijXlG3VthOvNNXD2H53tut8JUxCTLoU74pGYyL3btGFE6ETnuVzV+kRAVksYkw0TmtkF6CbYwdwYKWg3FztZVS/V8klMQBDY5+kA==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
