---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bullmq-redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    BULLMQ_REDIS_PASSWORD: AgAELNY7u8nxo1VIITQAQ93xxXo63ndd8Lpmdfyxxhb+jUx3sW1sb9I9g2s4SyZp+A2uh62REZQ1SzzHbI2j5FS5U/mlPYNcSPXpg5YklklLZNBCQVWJEShHZr4ARxWcx/sV4hqacoVJQrq376vz9RRiIE1Jfx4fT+j/OjfTV1SUwNGLESn/21CN7HYtlzaSYTiFBpUIiMsdzfVA7Jr2Wo1X4xibbTODNuBMhdMBgGzzN5K4QIbZjSDZa7dTkXwDLtZ2GNtgfEgJ3tqWxn9V3DsHM4Xg5OCEHHlLrzTiPiEe/S9zYQ43/pVrBGZa6Uu2/GiAPkHPjHcP1zAxTvwRNqngpA7uXbV0og3s9X8oKlDZm997xhnaRUkJgIu4BOeAFjPpgGn4DS9TL39z5N4cdGvXmB6eZxDXeCLR4TLzZ3qTQKnu2ZGEIP5vBYoZhNQIsBIrBavKp4TBY8M01AMawrAUhby1LN2RklG0leydTLDfIWs1mgH8FZ5D2nhdkwKOuD0BgcdhScdGGx/a3+OMFCmuZ6H8BmVrTfbty+Ow8Y6jvFiv4bPTPR0ak/q8GILpb3cLzKwHFDqcDiDIY3YxbtQdm78VmRC9bu3pv3QtnwR1+sN66R30qkFmpb38cYVl6ES9NaPJIugN4Y0oE9lddFMIbfc3NlYjvt4zFN5w00+ySJiNkdasKZNP8mq4nG7AAFDZFzbhqWVEwWW8tkuoBE8D4qsPKVBgLOMTvrL5L7SJjg==
  template:
    metadata:
      name: bullmq-redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
