---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgABI4n1qqhqGHGiyQ9En/HRKf4JB91xCK2WQDFY1U0xkYzELmIpNUqfXAb+LDuYKBlyTSZdOrD3GzEhy+Y8Afz0h9Vm40GuzsLoOLk7otw+WQWvjCzwdMxd9aZmOdO6gi8a6PDkYIOxfUruxKewjaGytldM1fS6LuI02bX3R4pXu2uwg2Ae8epsesIJxjgs/z7b3ntVKVG/xBel0o+gl1wCpUew0fcjzHefW3blUtDJr28oBAPyWqYGwQJCfsqD3ZGN1gI3QRHaFUVtXJczt3/bo2CfxDmEk0IZ78/fvy2vIAo87p8GU509/+6sT8KfneoJHmCNt8TJb0hAPbbK/m1fkmG6z8kGTJv/DJeWYCm6DrYKFSmWAmGXXDzUVmZKCB8/eZjPiRMwUsqgxRjM2lwNDXRWQOR22pAGHZwg9B9PXWkfzGr9ZhliVB7TRLdhsMuFGzUqs6kkJBbuUhOaVjP+bt7X+E7qDNRI+IEWNiL3IFmhrU1jDP//aP7hQHZ1FjMMgJj5p7sUnaWP0kLP6sSA+NUvw9bNn/9xlY0CXR4NG2IlfN1IHiScMMZLm670RZUpaGm5GaQf5f/ciMBWHcSkorRJsbeQPAtE4+nZOcUfdT9UWqmza/rSqzPRcNF+vNIo/RYBRPP5+GfcidDHfpkI8g+k3W7XI9NP+0zuiyaLL/eEJrMJPGi+OQzIZg7qlR918hQLrE89vFaImV5uxUc/dxCcTTZ85f1Lw91ldOpJEQ==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
