---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCdWZOx67J1tZbPW0ny8pCkuUsBi8dDGO+6vaEN2q68PCW0ylSyaoYgqjRs0AqWJyukJICQVftG224Yr+wYeAJcGglXMhPy7EFrbKGfbKgFdLQS3tVEYYXZcUtdd6uNXtiD9QnIVJFoJvRG3FvfNjn3eqRkA3Z1aMc2hPRTr/gaPvewdR9CsqTnaJMBmCZgyBISMrnN+xkVcB/7f0aM6syNG2RUssuj7OG7OSNbp8sGUpaG+49dKgNgXyJr32IESK4fzOYk6eAKKBYXfKBA6hXdVctf26dnd1ZUHLtuJ5YkK45ogTS0YoGOS6PWDF9+w5SelWdZL3um8gONX8vb4ioXb5oscYh/E/EQwLE4LMdhOvltx1r30ikOmXSd6GMIwtTLtMI3VRQW+0TQ/nt+zkL0Xwg9WXsBXY7Ymjt5PwfDv960HWrQyv9grr9q6pel3D6deTnELoWG/oRbyv265hV3sc8mf0TNU5DxYrg+bCjmi+hc0ejSUnib1kz3/8BBfcVEyoN7dwNAozv59AFv1BB5RylUvjTxOGpSmNF1unstVt6LT1lVVNG559COGRMnMlvl3Sp7ZyPTMTwPRqX9TasTKX9BFrs/NH025CjkrjOgpsPMKS9m4Sa35EjxFAnjHP7FybZvCnU5dNB+YevbeR6t7pXS2TiH1cDuYgAuUE0ONfqAo7RN02em5WHEIXOzQaJ9HJLIGE+LPj40n5mZTYHdM6xvPRV+/aGUmxk2cVdy+g==
    username: AgAJ5xeD4QjgbU4nKqNUXL1SZxTzVhMdsOHpySqhHcPkL6qCqeMf/tpo3O7xoeYsL0U0FwQeciSlu4Uonp7jLdg80++hAz03On69J4bRjWYzzK+xTpeTPLZcYnz5CXN3jnqW2sqd4j0yD6No+k8aIVzF/iZg7U0P7NOt300tcY0vZmzo/fr7bUPjtYAtBZhm671j2wzHgJk4XJjO7OIjEqUuxKCog+CEuW+xcuhbYfNnr6jgt3j2aFGu1XiCvv21QAsY2FX/yFrTVHX3kcqUl47bCARvNXt/Se+mgW3aPKVpQqfoAZxQd1AwYLrB3drmiOBhoj/Yhrp6tpjO8TbHtxcW1wUxh2pf0OFelYsUlcfpmT1KkjXt6KXcmeaLdZogPAHr59fuwegzVTNo2KTXFXpMPv3Ju9fQ7FutQbenoQcGiMOLxE0KczxxWypvj6RFZ+o8svAnDvubppuT6oP4Il+YgY7kwApkIlJWQV1bkzPck7GE04fOYxzFjPLcKYcjyvxglIG5UuB4n/OjMfoZtnuuIq89tC+zn3VxKj7c0u1zEgBr4Mg/hwZqSxWVuJkdYHRqQNAaXq4qofMpzhnWFmq0np0OuIDdz19ApYF8tWp/VIlJoIlYgin7tN7lxxWQQA6UhbPPgyIFOqCv+GS/VmRZcBLfK0jxehCQF++MNW8qiolVdYIYZXSgb+jmQPfuhnw+yowpbb+2aF4uBBsnhmTuP9lF
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
