---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bullmq-redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    BULLMQ_REDIS_PASSWORD: AgCroFbXWTVm36huwqeIL9FJKG2XQFE+A4/OFwr47POL0oXNQ3IQe/9BkuYLKz9h1GgGoPq0xa9u3cSGB98lLi4kvxguAQ7bVyIbZmVw6uRHftf6ZzkMXgC/5lFsORCrnO0sZxslDce5vxVf6gbxnSRUxO3+/MHC1NJh3Faj4wb3z/QQ4f04dXrnmFhIKZ6FTAda18YtaLvSGc12f/j9ymj8U09AIMoOaJ//pDeBhPVN1n6P0YnwLyoNpTXg8ldyJa65BKBmr26Egj8+AoAAS0NNM6fwTEW4j5oRMN0vUnTLOePwgJuJFjwzhJw45PJPhsJfwWmZooLLfkPwtQepaI4zOPzdyLvIBQPQ5ahbKV+TgueFoSeIVRryk0Eln3gpbWYYq/m9XoGsY2acTJDVri6QToQkwNfZXH6iPjxKbeusTkO4rEJgajaqQwPxeFKvXFPEItrAXbf8w86Wl7G7kfco6KMnDC90WUIhoaf0GlT+ZndLeqtCk/hUKeMJoaQcOE6AxDoARf1CQLjk2jTa5ybRuxJd8vfJvqLlDE7x7rlwcYjCYoCAtqOuZWY0PRmeOo9RyXijCvmAx4Wj+yCKxCz4502hYdO6nXmItjjpGyhx0/JMiMHTYzA7EHQzu2PLxIPZSeDSq1pSAScJHVA/C0/CIe7/FhGvsEwdiXknKCPPMX7Jpx/eHRZGlBN7BZw4I9cg6/m+5kSK1X0V4EqVPaMPM4L2h+t/iL2T63W+nl7j1g==
  template:
    metadata:
      name: bullmq-redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
