---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bullmq-redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    BULLMQ_REDIS_PASSWORD: AgCe4ZHgzsvbtIS4toCs+qBQMbPKMNDAYTd0D1yrEI5EUMbNs0AhiKLO91s63I7SxByp47YlT5y+Ko+Sr86Y3JYy2ySzdu2YamfzkA2NJUddPRcKr4eLeS0c62FkpVerHxZvkt9ilTiHjzimrqH6PEWDtkHvQ+cKhOXkFn5NZhbXgbSJGerdECgyzOY5LqKFJ/pagr1hB5MzmFPXFORfo4UOMN5zWfs1T0T2AQYa3UnF1i62+wwiTdQJNVhbeGwAJWnkzcf3k/XfjJ8KAh8ec8JpuaIDNGf8t+yXxzdh3cyOVHyrM+7H/vLWaBhN3FWDp27R+nUNfb4q1NCOgWo1VRox3LQKa4p95z1P4dQ9mTH41AqeJG5IXbM+Z8kft+R56PyGysEVfLZ3ox9F64A3s+jQAF5P4cXhbUL7YJb5mtlemqVO7+vXuqZ09cmsqdCJFvtpoMXZT42ckI3iPO/leVd6f6WVL0gr8rwudEUtjAC+Q7bFdEDLa1LL7X14f+icgcIw05LY8RP06Wp4jr9p60Afmkqx1q8nOoQm3WiK4/Iehe9TPwP95gn7W7/5RN2C5TwaQ3uN7Cbm0o/ewlKRQaUfNU8+RwJwxA2uUQoOIa7HD4exGHezcQkk3tUQEN19f/JPK7hqxokDEuF6+tEqa4fY77sAd8BbcJERg8kZCtiRwJUDkHk0LBL8Z9W1fy6VhySk+3CXbK6qkfUUTC5WJ9c4vaDvwt5/DGTBh/WnOqZ3VQ==
  template:
    metadata:
      name: bullmq-redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
