---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAvoBeYECX4dShkoTDjo0otaVTFtTZ4y9NsgiYmET8Cdp1TqoPpufzktc7XLgoHiBYPum+KoPKimLrOnNAv+W+mF6LKta2rqelcG4Sznr6gLNR6nIS89okw4XNMkDfKeTJojandjPPx+1IbdUrCQb0gyiNTAuHDtQoD8+ghqTJ+Bq3thuRflHhzYkhXYkTEXUZlJJbGF3LAnadfHAvNyUCxn4vFBX1HkzsFTvUc1bNibmRJy+mMmvdV8F5owdJKgdnAMKxZjl8m08RDzGwGi/NX9SMAB6Og+12Z1oWmHN3JWstUlf+mW4lXj/NIsXNUD8dZpkPdEvpmehtHCUHzB/cA8WNlxRmzd+g9GJjNvGnckG0tBNIX4jqSwtqDnG6FPfA1QZFXFrdfvUHW+jugmz2DozQ0roqxwX3StIunA8CoDy5fw/ajAJlCUQPvV7CuF164REpWiXnUMorpwYwYSUmuiUcJFpxbKbN+kVncxskQo73w9rEb9wlIa3b51AHWfqr+rdO4Nmy3bKOPMqukqKFwfoBOOtMFmG4ez5NbM92+hwqjjSTi3x0TpCtjee0yOhDRuJQl16k0PXfa2FmqB3ocCr3xYLloYzjsWQBJ3EzGCXWfINnw3sZsR9nlp4A0Iqlc6aE1FdmxmgS5Iwtl8FDPNMQ5YVfi9u48iLh8UPn62TNjOH1B06CTwHyTcAAoUJ5ZHp59MrnMThhmnN8c4vNhtkhrC01QtVnl1gfxJNvK/g==
    username: AgCH8tWtYFqn4u0BcO/3N3VnC3+DeWmlPe3u8FU+ke1YjZ0yLa7Ddc/Q1CMOwMYa6o08VlsilHmj5ezXNRszU9Yx1TTCFZw5U6lMhz0ikchWFizgpDZFD0qjZdqO+CW/sGIxe/NtA2sBQ+n9exEoWoBmESVohm5j19ko8QEu29eWJrRojaHor0d7QN5ptASBK3hvpHLeurpL9D6zcyf5Vmj15ll03nDWRd7xEM0SRdGEcxTchmSHFyrbzh1fgSOyJE9e7NUACpdu2plLnqAR8BMkLk4qGb8fL5jsj/hAhOeEbVfq8FsLeN6gHAdQoGSWtYeMCbfWpPswtWZUgoNKQaetkAFL8QJQhMR+g/qSdc4ytFeQivJrhiRrIoapObd84hTd6maWpJv28kj1kF3A8Pq7Z0whogvFhL7Anp1Ik6Hrt/7Pm4czhBgQ2SjIqrKZxbGSP8Ma3xr/7aobgy21mMw8n1GYHNO9h2zw8NonrQTaUw9sRdcq0Iuvxg4IaWnkJoztiM5cH2poddsO7WkfdDCWhRc2hIEFVThewKs0jyorqppVwi5O8k63anIf/9JKt4yaMUO2FilA07aH2jIOXNV8UKmBt59CSACP+y9iYZaVeq7If9K9X8DS6N7bAheV7BMW+iQXqJdxAeTvYz6JZKeNR2zQBD04aKeAToSz6U/FPIMubcLB7rMxZASurDgwEMPQKYjVpnspSvHT1+Bt1lZkfEUk7gaPt+FR/qFZHA==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
