---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCc5ocSUCOFZvsVD5NK/7inilviBi5Bm7ahT9azTUyLDZpIZKB/M4UQ3E/+U96x/0i565QXQvkMLYIAdayUlKl6bivFSTw6SOpn6SIGpcUvi1WXvgj+hhpZ7EKwgNB/uq6F7CEiGCZVcEOTRSGjrLPnqAUWHsI075wy3kUVJPDjPLSu2PEzkbZGCYdm/Wr0SEFGlI6oGfUmDKMqI81PNI9nMImrNlRsM/Fy8J4CGzd8q5AZF+MDhiBZdA1e8lr1K698TU/ZbVCgjZFcczAu0NFrB8EYxfj4sqdG2rpi4D+zVogc7KBv0JEDaVntLxWLBzSDRcGy1v/WhwptDf1nxlLyACBAhxGoisxPJSS/0nO9LtXqWi6Fej+GWMVur9fR0LKfuFU0yK23FRNbE2a6WBkubZd1MAfPrbTz00f6BATKjjnbB89rYU7pAa5ZuXn9zNXCc0pJZRTxMYcmkehytj4v7TYw2yl1e5DUcgWb/WPovSNvOR/593bh2LufQroq2h4JG6vn73AFYNld8UNSV1WfzcSP3uOabIV94Tw3W3fGxfsmythE5l+s7yVr2UnwBryjAk6MCRjQ7c2O83KjgDCYGd+9z5UXQshlXSshfzM3w4XKhyPxsQNLBYxa2+yLO1b+L9HeVha8d6RQfsYU355VEL8MSXSfhhoLDAhAtGU8uPf9Ze4ZecmnG8ABIAPlYU+jslHerPNxUn0mjY+7FL/smgmyXIu3hdbwJTrdOUdOBc/QJiiHLyWFaYBjowfB7JUs5T0Zn2hsldiKRBt41Mas9K5EGK1/1jpQntxVwiOjw7N0nn9oBIbRqUFcOqUCq+zYzIyAs85IEa4i5t0WbphABdwEJIa/BV8C80WLuNZujRfmGhZ/IRYC5Gw8azn8039fHjhGuYOARC63tQcNF62Rn/HAkV85QiF23DBRBksIpI6FfjOwD/7mHw==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
