---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgB1ReRLLKHnYuwcFPJI5OI7il0WOi7a01xR551p7jzbY+HiV7RIaD+4vQAcDdImb2PF2m5BAVwk9If0PzbHP4MGwzfqJa+4YVVmtibiDBIocmImZwLWm5655Rf5w36H7H0V3EL60dEMBWEjP1M4gx5tr3z13KZDbasXGqQqRrwnSWrZvYcUNyWF6Ab6z9SDR5d5gt4iOqdEKXQopTv7eIbs521oAxznBA/t4eXLhBtHLwSSVsL79DNSRgFLltXnCYqMKy2+YZ/H/6syPMKCh8EaiTEfBiVM5aI8MVorwjDvb8uTw9ICJONbAUxaWsVWWjzKzP7YKr8iZsdNeIBxpqqjAA7XTXIaQ/GNbr1h9URRL1IKnoc47tarl5oVHUWEUkPuGG2zD1o/VekbZ1eG8MZrvp0qAU97UUH8ODKTcnw31GWA5fBT5UOk/HcDmHoZasGMTxa1T5QjhavhuSCRVWKvH3HypFgXYRVB9J/SVDm2FEq4dTtOc3ZbEPMucL9MV/TWcACWFpqayOBIKpN9I33DshCmFerPpwr0Q43oyjWv1JLPCIj0HC7/9d1V+evX+mEpt21j15GaGtQ9F+hJzCRNTXwQQw6AhV3I4mzoXs9SaMPff2XdBjbm0sKHbtmqLivxjzJQnnS8NgNlEKAVcsDCxid+KkhbZCLTsinfnzHXfUL+g3O1siyQWD8gH9kPMC0i3pVAKM5FaBDBU290GNR4B/GaqUKle7WuQ5N47+TbMQ==
    username: AgBuL59ESUvFb/NjzH1BvvjrJKCI/Mn/0KcgZmykILrQfzI25XhStSgNw7bOlvaeXBz4mWOSO8lDvIV0LgxTAmeJnRrjUPP4skwsZTl8PfEymY6Ym4tlysp6e0ZO57G8x7LU3EwtCZp7eyn4JHweadJXbbcGCzL9ScJXCABMRjHPPXDVO12xNkkIEOKN3dr1wFF71kQvqsRpBDaQA/FS03WM22Kl7qMwlj3ilqL7Z9Pa7Xaa6PKh6cVMbXR9N+D+aWrngZN6Y5d3kd2GG8bBzTTGPz5Gn7lFod1yWevgjFXwILoFVpfFEIOoJRsXfZjAmDPlPeWjaY2McFJI+ePE/HwVHcZdzYnl7xzQDF0gvPfVFyqLvRAYw5q/4C9ulnkXBTsiqJR24S68m/EkaRv8pA06gayGKxyRA4u3t4EBNZJnOipeNkACMEs2HaOW8q4X86ePF038lhJmoxH8Eh+k+Qif4NTUDXzEBrqgxGu2gLBmmZSQ9FvMO0MbAeMPEsysHt09zB/43cT3VbjJr9IQoo74Piy4dgueTDB0JHmDeXTTrPP0zyR5bPk4Wijo4B1z5X7p2HYiIhCVaAHnSyL+LxCbBDrUJvYs373cXYC1srXkgHX0BiebwExbs3TkwjcIR7YWfVELuCDJzjD7PAcjFrrW35VH8emIiClm7/hQdZjIG9sXm4wjRF3PANryBmSYxJ2pn7u+0bUnYxh6B7ruSwi2DDOl
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
