---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCnzeV1F2VQdsOAJoIuAFOKkk8vLCrc7Bb1vg9gd/Djl8o5U/81d/RTlO4GPE4eh2g5RAvu1rkrJyCCTD4ik8nif2EJktqeyAA4p6+AZqS5pmLqXHtkTeA59nJmYdjRk5oIbrzQX471GvIXHouqNOOwUbsTdkuBuICd0M6dCuIYIdemlRoValrYYt4UUhJcFnjhyFhToyBGZtYi9HFLX8LqCLkVD7pceGFt8mQMZWqsZdGeNALmW+3MuVCGTQLrwtDRh7FqkH8m/XubJAmKHOGn2nCwHEHoedvZT4iLf8eWAOpmGgaryFb4G8+DoiIH/wXZVs3XLk9QWPpOXInLSsUDljnejtilWoNRuhO2gW7J50fFBpGvziqR1cekU/VjSebr31cB+bIJz2OM6FTuGlEH9cLFGNHuZ0kHfww2MDY2/mLuBCaF9cN3u1AnFcOpETFzsCCiB0aip2JjmzdXOvDeurJKNWlN0OWcF2OlZUJia0J/dEYpQxyA++HYyPf3kvQFpoXiFETgAsrphXthxLUdUKpSa29aT8+a1YvbId3qRLZhCE9YW88QUELet5pk9CMuj7uisFLOYbrxBK0tkAR5MXzBPcEnVZhsdPeltto6F3AGpdeI4bempRkbnpinWKV7VNrXmpErmhIikyjmh9DyTDtnFDDTiLkwnfjQqgKxTrwwvA/iZMLQv+qVHI/OxXTwr2hgjXE5KG6rqgV8IlL/WjncpSd1TspI23sBU4BbbTX/GPywssu6XrIjPluAYkdIxC2PRuFOOvlSxz1ioAbTH+PvGJ+6QWpkFhxyuseSZNuVN+X7KzAg3N53HXRpBm5k+OL5wMHEbcQybUgHTezcLR7jR8/6ftV+8894w0N4ajn3mtEHKsBIvr8XfRNIq0N1lP0ul61JPtyMIZO2N95dAx5760hgqkuQI0cx6l4VHAPaI5wrtm2z9w==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
