---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCnQ6eAWZJddBxlc1nPitK/PKpA7/gFeQX5opz6KAIq7l0t5fLvjAP7xohHCp4wrmdh1RXWfmnGs3qzuiHHr3bjwuqfMFvaynonVZEgNzmSX2VOwY5tIJ7GwQh8wRyawa0mCvNPpEm/lOubB+BmIItNEQr9C/YPvRKIxlSKzTGQhmTv62xrU5yXr7Jn+NC8zI31PMv/Kn9ddC2Jq53VyoMUs5SNiuX/OmB0/iwdjvfEwwTrB4wy005xFSXH9cb1bbNAySHU1zNdrwCpU54l3Bdqd1wuxarS3CNKSsHbE976e13fyIKyJNgE8CbeFHSd0uBtdlRAodxkVtN/qO4D/aMZYhddECVlmEPOagfWI3kVPL2RB0d3UUjpNTMujL7qJrZ25//zI7708XiTCZRIRMx+tLdYcu9JDuaXvAYfzZh8uj07ttuIe8WLVUhdrPNj/s2iaHgmve2zcCO5UHcWTfj9/e9u0MNGvb1GHDFas0WLe5LsOV/OWXmXpn5+A11uqxb84i0yOKXsVwIonEOP/Si5ujEzJeCCOdKz3gm/HqYDqLB4Mx1VdFaMEfFN3bqTBk5m2sUbGuEpHbhiWck9lqpgthT+NlMvs9oIGXnQcDF1phzWi/mIMmxSb3bhCdgxtLzC7lb7HZRb2fCw/6Umr3RkPlQkB//+OwrjQe46/0O7/HL8wv0dlQUbBE+gKWXVk0HDMGN+rFQXhOSv174BAZJgGRXap253Ww6EQ8hEU/4StA==
    username: AgCdGTjOigTlepimhemdVV5ZpcFfFsbqFm3dkkujKXY2mfH0AIk7hP6LPWM3AtEBXq3u/qpf8M32ntumFU+frw7Rof1UelcIuvv3lnv9VO1j3qru6OJhcB6KzdZDpbXPXHJnH7nwNodp81GxbfqOFpbeEQZ5l8UWMUS18J25nOl6flgIdnD9w1ZfBJcNd/kVQlYd5oDuqQlEI37SeQRBfXrmI2r/UUd5K3A3LiFSjqHRYbw6nFEVBGsYSYaH9SwQnbCTQ8qPyMQN1rMaKcc5YhCBFnVvR5Cm0DR9IaVZ34FipN4v3kpUEGCOjB5PQWFw22JDRq9DwAxcvlFTKZQ41POU7Z0fKMWNTV7ySFSHHkzGQvTXpGOKmzotkV2n/0BvLohbK5nPRl6Sbei6Nw830tc6Asounr1bf+IsedX388pZ64d3YRohpY3t8m2VqYH5dHXAuuvfsd68OIrqrAWdpwSMOrFsT5igxPHQ49utb3ENf85Ycx0fwNW2F351vplyKtDIQpdBlj0DZlR80l3CdN0A8DpnhCuHHc5XROzsWmZG5/mafvrHZaTDchbyeqXUAP1zg7+8TLh5aqgWsy8+sghcGK9uA5O1HWSrHF5qOdslGpxAZsLkk3HtN8R4aikuUzzK/FWUy6OZitExdC7O7e++nARncoN1Wg1DrAiJuBf94R+CRKa3e1p8EfMiGvNGeqzAC1l3sgoWvVw8GSxjvo2XdAPAecrH9Zg=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
