{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "chronos-ngo-dev-meilisearch-search-credentials",
    "namespace": "transparenta-eu-dev",
    "labels": {
      "ngos.transparenta.eu/search-key-uid": "a918377b-ce16-4074-929d-f99ca11dd800"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "chronos-ngo-dev-meilisearch-search-credentials",
        "namespace": "transparenta-eu-dev",
        "labels": {
          "app.kubernetes.io/environment": "development",
          "app.kubernetes.io/name": "hack-for-facts-eb-server",
          "app.kubernetes.io/part-of": "transparenta-eu",
          "ngos.transparenta.eu/search-key-uid": "a918377b-ce16-4074-929d-f99ca11dd800"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "apiKey": "AgCRpnDVIDndXLRtyJz8j9ajjIQFjTOYZhrO46lsrZKYufEr2e/rvlCE42w3/xL/6cPJECPy+X3YnhN8mJ/hg/0ewn6ZPbkH8c+6emX1CfKfLrys+qNXzRQXvJ5hpv0Fa87BLivVn6ij9AG7uqjcIhq2T94qWvB0RGptqeTN3X9V+3JQRDMUNYIc/5CihpFIKXXd8nwVsdpuPb89HALkyCKXWYQCfXErmiCfKnBEOFi2fMfiLDCdd/Q6SZ2CnIBDU+LBefMuVAno8Sybhn861DuutJb0EP8vC5HxkYZaG8wEqn0UOvYbXNC+cwxi1Vuq7BAedNFZCP0WaTWN7L7uCG3pZxWWI4BImeFyZHWR0JisFxCQQ3p1vAdAImDiPcWLP3/AlBZU+vEUHE+l4t2tfJlCCtl6SmbOCAj5qjX9So0BsW2aBxuI3RoOMiDmeB4eTTrAoc0OgHsYBhGRV5wZHBQy+RgpdP5nbMfrDkxKFewDy7QtugwV9+LcajBcjKOMRYs3BzSzLhlOdcRk2wD+LFtxZamIbbJW9hANHQhSp0n27zYC7dDdBR5d3lD4qP2qzJnOJE+ax+dMhtPkZpYIq/6kO3QXE3ZNAp1vM0jC7MyPM1cjrAjMb9usHs/2LBQt5NHVmZMonlqplA/gK3/HvkACxT6SUzQRcOxyO7AffEKusmfvYDdr0xBr8HMYxjShhvcYS8Qy59i6EP/wd848qFYcAO2aDVso+Gf9bwzJvprM6ichpGF7jvNWRNrQ1Aum5MRI+FwIwVV8ePARl9ZqEDcI"
    }
  }
}
