{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "chronos-companies-clickhouse-reader-credentials",
    "namespace": "transparenta-eu-dev"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "chronos-companies-clickhouse-reader-credentials",
        "namespace": "transparenta-eu-dev"
      },
      "type": "kubernetes.io/basic-auth"
    },
    "encryptedData": {
      "password": "AgAMAy/tImBwLZbIdWZVFeDy85nUZzaMhSVb/n0eBPKHB9CzpTCgap9oHr5cxabWt+fsJMlFM/uz5ayloxwdkyXgQoOq4/H485Bv4EqdNEWXwIXsU/MYH4v2lxe3lPJ/j88bGU7rqOPw0X+LL5eKBYSzV3kGK+Mo2+CTbVudUWiJ/6fAm7FPKTSj8qYKjYYD657fGfEEY3max6GX568/yJT2TgO9YXAedflkR0TTvzaeUt2y6tbwU0SOwdL74e2GEZyOSK+JyZZ5aE9iaap+Fcq+PvcM9WMapYjTVi4i1BS2W55pYplwCO8bNNBssCLMtAu+BAJaLufyUw1OAl7lUT7mOem7rhFgZ/Cev2da7g/8z4uHRyoEqmKskFvZNiPzzKZpmr1lOYQSODXyg7Nt3h1mQPKT9nHCmXvSjv+olXbnOI+pxdgGGMKcBBrqfQ/azbVrjPFHV6MO9FrJ85KDNnTB29KqS9mUeFYcdM1a0lc0UkMih8LSDSTSzpeFIoEYHztj7zLrKjmkGcD2YQPWH/P4yQtAJU84kw7ImG5K0hM91wqmVPcZRZD5/6/igk3pdqmHjpDle3gTuA9aHv6wowpuPuGLV2RVe5nmX16DoR8knAJ7baYVsd7bu+rq3UCsPdF/weNPbjJb9lIEh2anZrTt0ZCIbxSOBsOwkYkmBqs+QYFUCSjeJ2P7C3lMqeO1QymBvNy60wfcn69vBovaStOnXbEN4M/EthS6oZ0ZG9Vh+QTzoSyhpJKGAggh7zp8PuU=",
      "username": "AgB8iQAF2evdd0zGVm0kVgSXokIs8Uxt6Gm7qjW6j9IjkDcxOMnl9RsKJUiPQBjlbDVfSTivuMvzrmv2FtoGB9jeQlDBK+rIjUYv51b+UNW0AMMp0mYS1yurz21Epktysre+g5pi2xs6ZJVZJBrLVPg68iYZn9naOyXL3p2gFWR9++dtnFpumtp0yN/0ChufX/HcEi4Rq3Oi5k0e4h0nRggLclg7g5gPCQlWdNH0YuGwTDnJMrWyfaUsXG/wL0i0mtcPkLLtzsXuiI5G6kgsNMTpNojl6hQj+0YfGuEDAONCPYipIkQdiXnR1vRdbDYuDGspmC5euO+RqAc7LYvRTmxemdlsvyEIrmn6qmdgafUrVTzrNE075SqOyBFcC1Hm1NclCi7m+HEr+DFushBivc+QiANBbWG0R8euB7JQTx8EdcxsNVLMT/egTOuUBrHPijlCCqIUCBC3wg1MdI9xp9c/j+BYs76E16r6QYoBMS6/L+rvBVC+g7cAJT6SSdvM+DZHoBC2j13pefs0wyR+5MyY6pdg2gtAgLezJ6HoVirInZuOxkJx0G3qqIbv0XHEucGY3F/VFjnVtU0EKXoGHavpSqKfZgXf2vKnpIvPsQ2bkmh8XLXxitF78LE953yf1drpJca9m5LIhlmD5IFWS1wdIzauyNxyrkithZyR/Vf6Ejguf2K/mp2oei5SSE1qUJRmISY4U1J0abICE0YJxHO7"
    }
  }
}
