{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "chronos-companies-dev-meilisearch-reader",
    "namespace": "transparenta-eu-dev"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "chronos-companies-dev-meilisearch-reader",
        "namespace": "transparenta-eu-dev",
        "labels": {
          "app.kubernetes.io/environment": "development",
          "app.kubernetes.io/name": "hack-for-facts-eb-server",
          "app.kubernetes.io/part-of": "transparenta-eu"
        },
        "annotations": {
          "argocd.argoproj.io/sync-wave": "-8"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "apiKey": "AgBjqgYumnVYVbR+WeunCTLqahPRkXS/Yw1Wf378fX+E5t08tRUo5uks3jKBYjSll5NHmcuAfn8qPl5fevy2lJRDT9GcEDUKkkt3NeUZRVUfme1SBqMDyTLpLnhlN32WvAVTCyt4QdTtcYQPzEwhWF8w3bmTvyrMhdMyM2wjmYLXeuGRFKPJ+yriQ1Yvr9QRIWKJ70KJaQoHOAVGOCIMKotZRKdkmMAMdPEqoF//ba2C4K92MYK58SfS3sX4BQB95lPJ59LwGunOLDAN9zAh5Q2xZj7xc9Il5bxJc7lm6oouTuflB5l5bkc+61oTsmtXoE6XCAScy+5OTwmfvEKskuKauHimg4OdihGgBci8qYq+Hplc1V6b0en2ThL8cudQG/0yydxj+nPVh67HOM3sS6kG9tYRueiW5Gx7hCae2DteHm0zh6BiSn9avv4w5aBENZ96rWHQPfQKDPAO2lFrU77h3tXsmzFi/0VKg0z+awXobvmAAmtzNjxOgRnqx8IsQjejsU7BivYW+9nFL7zJTncKJNkZG9tTmgUCv0BWSYxn7O9hC7kqbSuyoJtb1Gob3Ej4mSnR7uQxMt3J+VP1dabEM6D7G8gRHXzKYwfdAbSJzLcGxTZCPTw/44Fdy4/6oYyGuvfn8kFPqiPYOINIkJsJ7zuclDnN5PSfJSpk25BeBlNvviCPMK35lnJhKOVfhmoLBY8O+bpWBa9g8gaQ3dkUTw+IjyMqj6mU7jjEYyhPDsXam0aPjScp70HWKFNN6hISgvYTUug20gXESj0dR60O"
    }
  }
}
