---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chronos-prod-meilisearch-search-credentials
  namespace: transparenta-eu-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  encryptedData:
    apiKey: AgC5DSnv0JavxKzvA6o0NeESsQVCn/WtmxHcjCK0LC7edZTDY4k5Tf+ga19OcX8YaNT9JlNanh1kWmT3dKGw0ISyBvGHBmy7luOLPS5oRadV7aaK2/fGU5fc9NCEx3LFK+XvMP4RKd1zdTV2VdnQvTo8uthwIsmKBV2qzCSjbHXN8X3rGSgtzSE6S4CBBbTbMCRUYMJzBRR/RCtkY95GX5R+X2CvK4TXBI388Pj75VULlITBx6m6Y63usWPpI5EyPjiJ0/gNLeyYVuOqgk9RLYYay5YlN4TLUPWC13iy5OMNPQbCwWhVWI2ZqyqQ+R/z6EDKLrqsj/td8mTOkhIl2wdJzOZH5y5NBlLxLViR82F2dfQ7kKv1IP3uTdHajHKXqzVxJHEI39sBdwazd7WY+IE5ZAx8XuAoNftz58F32R4JgtoaP5HamJTy6CzFNpO/aCbKJRfofP0lvqyz51lQEifWRS6qxSYDBZ7zXYJOmaH7tlFnIpKulXl6YPENWmb492kFmY/nu+J123Hwb2DyqddqhzuAFw0osOMIhNep4U1Ak+foOyeqLgNk8k2oPdqSxl514516v4EwvTUMOS+QtTxGYS88+MjY5+r3lNSKN/mEm5Jt43n2AVpjCIb31scrlBTQY9H2Q/Qehi7jx/HFypgoDtJ6EEnXLJTJkMa7jGunIGttxRiqerdB0vWu0/E6UWwrxrihw6bdSIpxP7CdlWpYnPoXQADHWi1qyZ73bmfNtOVPOTmDwN4d7Jn17lNf7EEOgdZ2ybBJvkYS3u9+jjB0
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: development
        app.kubernetes.io/name: hack-for-facts-eb-server
        app.kubernetes.io/part-of: transparenta-eu
      name: chronos-prod-meilisearch-search-credentials
      namespace: transparenta-eu-dev
    type: Opaque
