---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chronos-prod-meilisearch-search-credentials
  namespace: transparenta-eu-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  encryptedData:
    apiKey: AgC6uoA8i0xoByxFNa/EIubJ29pidgZpab2DeO54UgMRLpmd3SLzecFkNRFMKLoKusyE0Hp3eOuY7cLxTYUKkAhovdohyjhVZaCQfF0WlpynQA2SoXpQOa+FLSDlzKPtlrdNWdZtb2iLHsHE50HSNRLfioz7vutGS8eGvqPw47Ym+pDlbqDVk183sCdZ1LVtpbznmhzTfKDzzFLsS+vguRE9aU/qqvnPGwO8U4nMTH9T7QBBIfyZeNENF+x13yW4idaFdQCgz6G/p9NZMQy95PqENrq6fd22QB43320iVjLPAqrUEi5MH16Xr4pbocVI9rx5xRXEGItNkmjnmFLEYqWI1hYTCnodKaNKvvdUf2g4XaoKIK/RleFmMq1VjI+8iM5teslyItHsKODmkst+2V1vPb4vkc8EnkH4VcQEfqgMR66gN1ymZn4oepc+e1IFeog8fee1IwhSIgNaY+WFPM3lgHur+Gl24Je+7Uw815XazQzNCCRX+xalwGceVAClbjlh9k15V0Q2N8xolJIWzfjMvZ60QByTWR52JLvqM+FbzEPuQXffFmSypZnid04OCFAquOZdpz/w1S5jTiUcXnXyHl5LdiuHSVFIoVwGWVNvB+1s2+YhdKQZue5m/wizllCthLK3Rb1x1p1XlhXzdaO8+DPzu/1SbReUtsiQd32POJUWFTbdjmMdw6X8TBa9WS3dbOvnBSoyZ4RHazNNNYyoJlYLuoa0gSjDgSskHFhf36FPRwbEKlPnMqQ3/dv0sjiasXRO5ffV+iSXlQlBmDrJ
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: development
        app.kubernetes.io/name: hack-for-facts-eb-server
        app.kubernetes.io/part-of: transparenta-eu
      name: chronos-prod-meilisearch-search-credentials
      namespace: transparenta-eu-dev
    type: Opaque
