---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hack-for-facts-eb-server-secrets
  namespace: transparenta-eu-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  encryptedData:
    PROD_DATABASE_URL: AgBqQb4M+bsdW8eel2Nucq99oSWgdFWlQ0sp9ghQVrx5FJrDkKYoEiqHKUtxd7SdqZbDgowkVzmvmTGGqcDgUyjFi6580Uzgj5ldWGkBwHSUgC/qYOd+MXTXTDn6vi2V0Bc6JOkExm2eEpYJ6uMTtJVephI+cUB+kVq+N/4y7/3Fvghq9QH4JZtGTWiYqVucwt+KNURdHw27QGVThc8EwMNRvQc6Kt7PAy845EH5kqwIKMMKv7RRGhzXjaDyh9c2eRpfAd2swN6RWNoLP7S05QK0c/PdHsoKxqgC753d2U7fI6OA1szd1NbUz7ZeRVZ1kBaXJsYQPZ7YS2jd31ekF40K+bR/Hpe9668AAUvkVbqk//4I5XP+gaffqvu35+o0PILo6cRHQim1UTgX1uESwVe8ImcbhhB7UVZDrF5SyFD2G43Xx34mzkssejb0aW3COkniPWPxWYbmU9J3afdbJ3OVdmcyF9J2aL3SeaRDhFwGhiz/iLod1S+USAU4QPSfxu/UXibvJ+EHfUluSJkGemU9V8UzG2nF7NlnFXnOfgrC0pAKwYGniIzWouh69eeQ97knReUAy6J7ZVy6k5yHDO2WMR1Ox6ZnFnq3piCi8Fptqx/xc0DHCo/QqN6LDxbv4YOQBP3sPVv4T4HkO+FMG+SNFUB0y7sfoGgOzZIjhKT7e2B1cc9ZIwt2oQ1K9FWjXdUt1hlAmJyHDTSlJ7bI+WC9hxA8ofoIVjc7NRrqa/8YfIchz/mvXqmPW5Xd0bpJy3aK5nHU7zPexC10GZrivY5+uIuMLYeiEAKlpWEISKsMqC9Qns8FBLOfXLyEWUAnPRf9FXmyppxIozchV8ovv+3aZdq90JWY3rCNjEfkw3AxAqI+f5+EHl26fIH/m8R2z5WeQYo8S47UeD/amplkLkC9X5HvrOFVvctLnyNX6Ov3gx79MIQhMxyVtqFmOs10QEkOluSrctz+av4QvdsIUHriGyjW
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: development
        app.kubernetes.io/name: hack-for-facts-eb-server
        app.kubernetes.io/part-of: transparenta-eu
      name: hack-for-facts-eb-server-secrets
      namespace: transparenta-eu-dev
    type: Opaque
