---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hack-for-facts-eb-server-secrets
  namespace: transparenta-eu-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  encryptedData:
    PROD_DATABASE_URL: AgC85YSP1IJN+9vp/PfLRRGZB7mMcCvQhCy8LholpRGUFYFcUzWeQaYn7yJ7qJWI6Opf1Vz4CY/vksRhWsAArFlkYhwF/K6orVIHWB7b34qWoPhsSUrXp5FTtui/mVncWbSEpah1iRWjkIAd7A4Oc5b7/J6N54wQxE+233Z1LFpGAwPq2pLmPGlR6kmQVOoSdNhH5D4lhezEdZl2lPk8x57PkFDzMp0y1H6DSpquRfkQVl0Lto87MvFQixv/HAvDbZRy0Dyi9jk5QhcEDDSbAjFi0j+OIxN4OHgGuKzL8pLJEP5pQ1fXlkBzy7VFp48bv5/97ULB/CWUgSbgZk5y4zql1LYsprcYvboE/TUJfP9l+o5tfZkY6tNoJX+m9u3R+6kbSRr+FY+GeTA3Ih3evBv/zEJYDy/+tO0U2ZhZGT6S9NOERdHODMKuQVICJluxzWeJaXTTqYbJgaF6dI8CM4F64WkYdXK92aX773DnXZLw+zS/m3kjxMwKgaZuEngAOQqDXBhax/+gHTlT3zeOzqtDItR2xmJB9eSBhV0o13V/iDRf9fpLPu/JiygUZnm6FA5IPgxn4x3jcnmxy09M9B1k7icUHo8xUHQB+Xus5j6P99CEjQIunvJ1SU9JXL/B2MGENF/3kIGuBa0EVVZV8ClkJI7gdWnM9VVJ7AhltpokqLBi2i1r61P5VwkWmBDKi7gWmCcFXIxRN4HLKj6YDPtIABsWn4v/tlhrBvhhj8yqGJ89f4o227FFQ+K1PXOcdz6JYx4E5YJnIDpZOdNHiI25GPSY8XnbmCmQJfDGIgorQRgTT6U7xGF03Yy0VOEhURix2sAEua+3ihjnpHihfocONH2Pg2nGXQ+UW2EIS6j3ENm5AZ5GRMx/wMVCDJje+ec4Qppq/gDPUQnAwtjRGF5bBOk5PiInHPLsOvPRs78LTkPB5Sb1BodoEwo3nDWMQ9po7XabMKDs98rpQFCIUGXqd4I0
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: development
        app.kubernetes.io/name: hack-for-facts-eb-server
        app.kubernetes.io/part-of: transparenta-eu
      name: hack-for-facts-eb-server-secrets
      namespace: transparenta-eu-dev
    type: Opaque
