apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - registry-credentials.sealed.yaml
  - hack-for-facts-eb-server-secrets.sealed.yaml
  - chronos-prod-meilisearch-search-credentials.sealed.yaml
  - chronos-prod-opensearch-reader-credentials.sealed.yaml
