---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: transparenta-eu-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  encryptedData:
    .dockerconfigjson: AgAYDfZzg06r5QXW4PZrEgMxD8S6M5GX6oTCSxHfaHR70su9Hw0awDQS/ruPxg55EdEDXPJlkAUQdQmrU/+TysM1O+SgP444RhW2J6JHP3+VMmKMoC6y9uekYu6SmCNwqEXlSovxyIH+vc5Eb0ngfkQdmMte071BmoMtK7sg7GUDk6FxGtThBCkr1Ix5mA/dw2lRugIBnS0syZBMVjBgRV9xX0tIqmUFUqgsn79coLGtumKxFYHhdnfwAIJuDIEyE5Xu2tAOy2OoVUje3jmuXHkw/FjN+qjg/Nh+of0XaowO8shtVYRLQlNjX7/I4/sLKmMPlYWNwXDN0e5joxmSc37hjaCw8VDrcDy6yWcKtajlYI1Lo5OgI/cm+LW/P5xVc1uPVOPGiIx0QgBV1jxequs7mzt5DEX1IZzMpv/MTNVs8kmiWbi59i1kbF4CVX/CzhzaEFBXTtMDGOItEKyOc9hKSsCBLFWfiV+K3bYyVyVgiYmhZD9dKZzkXqCeTDx/vQiIgrjyNf6yGgzzyUWQR9rrpJu4oaJPzl3scy8qm1B3sBlQbI3fEKfd4mUP2KZMTS1gNiGIK8AYds04wkObLZVf9JFPHtnrUQCkmqJhuFwbrmef4GaA3ka+C78oW5Ed1yhnwUtZnZcGCPGIWF99GSOdbrZsZISFcAFkI8bwtRl0i9/iFqY9mrcCcVC7jjmt3f38CoRenyE+EqGkkO338EXlnwljAnPclMNiQZzHRK6TfHBxDZUPiu1NQa2wYWwY9Z9ostUt9aRFcPUY2/gbPRKcH80dpEY+pJDyfODgToVP32j4Aj9i2ukmDAtIdLDAiQJ6Xi3E0GGykWqYhr45IO/0GZDke4/RZPhYm4VwmrXTYMI9IzVVclSjaH2OS0jHpitUx0vvQrrBzkPcNZC0ZBjhk/epx8vpqXp2TTFr90MNwCisIsGdzS3bZpyOkNQ/gm3XGnzL2h4G+LoOZov/nu32eCeKR1JBPfDOhg+HKprHkaYW1x5Fn/bBxR0YBTIoGT0XwWyscrxPMQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: development
        app.kubernetes.io/part-of: transparenta-eu
      name: registry-credentials
      namespace: transparenta-eu-dev
    type: kubernetes.io/dockerconfigjson
