---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: transparenta-eu-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  encryptedData:
    .dockerconfigjson: AgBtFsQb62mU4K+caNxIg26nRadWvHTW8t9SlGR/B7wDuMPUdwC9eoYmc71M/niwy/mw0i6SuHAzdCwlKgPOu6letUxDjLWhUwsyeiNS+5e9Hj5EFZRHMuAx7rTIDT4noEc0cns23VHUs5f+zepflTvw2OlKGRZniU6Uf4c9LK8EYxmek+54LvqMFGH5ZmW+e8R6xS67gL7Av8+0/aSTZP3czbRnDoZkpIRelHQCXWHPTajXYcgVhQFO59y2IZwj3D2Iy167JY2pqG49Pk15JwP4l8GtrC9F4BZcTRtnPMye/pQ3X1cNbqSS1o9SVXF0AlLuOE6twsLsri/FKkG9oytaeHteW7N0ZXnkrR/N0Bn/aEcx+7WWqCHU4POAe1hpyQdJVf0P0SkBMUF2iPLuAaLJMJkVMn65LWhtuyEWk0gR0Htu8Vdm1BA6tLdRiL6Ut0ycKbgOFq2aW5yJiC3ZBJpYV0IhsUZ0h1CzrqfXTwAzY8fupVF56vPTq6bkiVbpxkS/Gg0DpCUjrBM35uHZOSYQfUbTlHmoBSWAHYxGg9UWCHB5IND8PudS/YGFA0NaQcoIa1G5BeZSdBHOONUuO1CpeNtrM87ktrBmCiIrwILQ6uqZ8zw37nw87dESwhsdium0AyfSBAVn+T87nR0xyF0uKBYiymxe2Z74yXfBCn5IPXuIZnXtsInPovCnXtpmvCm3CO96uNDOFQd6bKw0WP0PUhiQMZcQf2/Et8GDUt9e9RZg+Szv9AoOr2OTLHjVjwe2npWjrfENxO3EPq9fJ2+Tjfj1KoWGZw0+/gKXIa+PxrFdYjevk4aD1G4vCYJasisuNHT5Ka0EmV9hfjnm1AoUlCKY+iq3Nmnfx7lt9KhAPFPUhasSY/UpMaVpnXkNoZrPgpUApHavCZG1wJiBrmhbf9ZUFvqa4nLH6sfdBJJbVaOMDAHl76FrnTc+pHfi4n+SmDvphZyoXaX6mWEfTFxo+UeGA7FAvQyLhJiSgQiSKv8bdTBZIHg5aAVkX5eU2OCZPD7tZzG7tg==
  template:
    metadata:
      labels:
        app.kubernetes.io/environment: development
        app.kubernetes.io/part-of: transparenta-eu
      name: registry-credentials
      namespace: transparenta-eu-dev
    type: kubernetes.io/dockerconfigjson
