apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hack-for-facts-eb-server-dev
  namespace: argocd
spec:
  project: hack-for-facts
  source:
    kustomize:
      commonAnnotationsEnvsubst: true
    repoURL: https://github.com/ClaudiuBogdan/hack-for-facts-eb-server
    targetRevision: dev
    path: ./k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hack-for-facts-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 