apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hack-for-facts-eb-server-prod
  namespace: argocd
spec:
  project: transparenta.eu
  source:
    kustomize:
      commonAnnotationsEnvsubst: true
    repoURL: https://github.com/ClaudiuBogdan/hack-for-facts-eb-server
    targetRevision: main
    path: ./k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hack-for-facts-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 