/**
 * MCP App widget build — bundles each `widgets/src/<name>/index.ts` (browser
 * TS + the ext-apps `App` bridge) into a single self-contained HTML document
 * and emits it as a committed `.gen.ts` module the kernel serves as a `ui://`
 * MCP resource. Rerun after editing widget sources:  pnpm widgets:build
 *
 * Self-contained HTML matters: MCP App iframes get a deny-by-default CSP
 * (inline script/style allowed, network blocked), so everything must inline.
 */

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildSync } from 'esbuild';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

interface WidgetSpec {
  readonly name: string;
  readonly title: string;
  readonly outFile: string;
  readonly exportName: string;
}

const WIDGETS: readonly WidgetSpec[] = [
  {
    name: 'entity-search',
    title: 'Transparenta — căutare entități',
    outFile: 'src/modules/shared/shell/mcp/widgets/entity-search.gen.ts',
    exportName: 'entitySearchWidgetHtml',
  },
  {
    name: 'entity-snapshot',
    title: 'Transparenta — profil entitate',
    outFile: 'src/modules/shared/shell/mcp/widgets/entity-snapshot.gen.ts',
    exportName: 'entitySnapshotWidgetHtml',
  },
  {
    name: 'budget-ranking',
    title: 'Transparenta — clasament bugetar',
    outFile: 'src/modules/budget/shell/mcp/widgets/budget-ranking.gen.ts',
    exportName: 'budgetRankingWidgetHtml',
  },
  {
    name: 'budget-timeseries',
    title: 'Transparenta — evoluție bugetară',
    outFile: 'src/modules/budget/shell/mcp/widgets/budget-timeseries.gen.ts',
    exportName: 'budgetTimeseriesWidgetHtml',
  },
  {
    name: 'budget-breakdown',
    title: 'Transparenta — structură pe clasificații',
    outFile: 'src/modules/budget/shell/mcp/widgets/budget-breakdown.gen.ts',
    exportName: 'budgetBreakdownWidgetHtml',
  },
];

/**
 * `</script>` / `</style>` inside inlined content would close the tag early
 * (the HTML parser matches end tags case-insensitively). `\/` is a legal
 * escape for `/` in both JS strings and CSS, so the content is unchanged.
 */
const escapeInlineScript = (js: string): string => js.replace(/<\/script/gi, '<\\/script');
const escapeInlineStyle = (css: string): string => css.replace(/<\/style/gi, '<\\/style');

for (const widget of WIDGETS) {
  const entry = join(repoRoot, 'widgets', 'src', widget.name, 'index.ts');
  const result = buildSync({
    entryPoints: [entry],
    bundle: true,
    minify: true,
    format: 'iife',
    target: 'es2021',
    write: false,
    legalComments: 'none',
  });
  const js = escapeInlineScript(result.outputFiles[0]?.text ?? '');
  const themeCss = escapeInlineStyle(
    readFileSync(join(repoRoot, 'widgets', 'src', 'lib', 'theme.css'), 'utf8')
  );
  const widgetCss = escapeInlineStyle(
    readFileSync(join(repoRoot, 'widgets', 'src', widget.name, 'style.css'), 'utf8')
  );

  const html = `<!doctype html>
<html lang="ro">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${widget.title}</title>
<style>
${themeCss}
${widgetCss}
</style>
</head>
<body>
<div id="root"></div>
<script>
${js}
</script>
</body>
</html>`;

  // Hosts treat the resource URI as a cache key (widget HTML may be prefetched
  // and cached), so the URI carries a content hash: any rebuild that changes
  // the HTML changes the URI and invalidates every host cache deterministically.
  const hash = createHash('sha256').update(html).digest('hex').slice(0, 12);
  const uri = `ui://transparenta/${widget.name}.${hash}.html`;

  const out = `// GENERATED by scripts/build-widgets.mts from widgets/src/${widget.name}/ — do not edit.
// Rebuild with: pnpm widgets:build
/* eslint-disable */
export const ${widget.exportName}: string = ${JSON.stringify(html)};
export const ${widget.exportName.replace(/Html$/, 'Uri')}: string = ${JSON.stringify(uri)};
`;

  const outPath = join(repoRoot, widget.outFile);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, out);
  console.log(
    `built widget ${widget.name} → ${widget.outFile} (${String(Math.round(html.length / 1024))} KB)`
  );
}
