apiVersion: v1
kind: ConfigMap
metadata:
  name: hack-for-facts-eb-server-config
  namespace: hack-for-facts
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  # Application Configuration
  APP_NAME: "hack-for-facts-eb-server"
  NODE_ENV: "production"
  APP_PORT: "3000"
  # CORS allowed origins (comma-separated full URLs). Example:
  #   https://app.example.com,https://www.example.com
  # ALLOWED_ORIGINS: "" # Set in overlays
  # Rate limiting
  RATE_LIMIT_MAX: "300"
  RATE_LIMIT_WINDOW: "1 minute"
  # Special service key & limits (use a Kubernetes Secret for the real key in overlays)
  SPECIAL_RATE_LIMIT_HEADER: "x-api-key"
  SPECIAL_RATE_LIMIT_MAX: "6000"
  
  # Logging Configuration
  LOG_LEVEL: "debug"
  LOG_BATCH_SIZE: "100"
  FLUSH_INTERVAL: "5000"
  
  # Observability Endpoints
  LOG_ENDPOINT: "https://otel.devostack.com/v1/logs"
  TRACE_ENDPOINT: "https://otel.devostack.com/v1/traces"
  
  # Kubernetes Cluster Information
  K8S_CLUSTER_NAME: "default" # This should be overridden in overlays
  