apiVersion: v1
kind: Service
metadata:
  name: hack-for-facts-eb-server
  namespace: hack-for-facts
spec:
  selector:
    app: hack-for-facts-eb-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
